'use client';
import {useEffect,useState} from 'react';
import {BrandLogo} from '@/components/brand-logo';
import {ERROR_LABELS} from '@/modules/analytics/common';
import type {AnalyticsReport} from '@/modules/analytics/report';
import './analytics.css';
const number=(v:number)=>v.toLocaleString('id-ID'),pct=(v:number|null)=>v===null?'—':v.toLocaleString('id-ID',{maximumFractionDigits:1})+'%',money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
const date=(v:string|number|null)=>v?new Date(v).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Jakarta'}):'—';
type Product=AnalyticsReport['products'][number];
function ProductBoard({title,rows,metric}:{title:string;rows:Product[];metric:'views'|'adds'}){return <section className="an-panel an-board"><h2>{title}</h2>{rows.length?<ol>{rows.map(p=><li key={p.id}><a href={'/produk/'+p.id}>{p.name}</a><span>{number(p[metric])} {metric==='views'?'views':'adds'}</span></li>)}</ol>:<p className="an-muted">Belum ada aktivitas.</p>}</section>}
export default function Analytics(){
 const [range,setRange]=useState('7d'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[applied,setApplied]=useState(''),[tab,setTab]=useState('Overview'),[data,setData]=useState<AnalyticsReport|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;const abort=new AbortController();setBusy(true);setError('');const params=new URLSearchParams({range});if(range==='custom'){const values=new URLSearchParams(applied);params.set('start',values.get('start')||'');params.set('end',values.get('end')||'');if(!applied){setData(null);setBusy(false);return}}
 fetch('/api/admin/analytics?'+params,{cache:'no-store',signal:abort.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error||'Analytics belum dapat dimuat.');if(active)setData(v)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false;abort.abort()}},[range,applied,refresh]);
 const k=data?.kpis;
 return <main className="analytics-shell"><header className="an-header"><div><a href="/admin" className="an-brand"><BrandLogo/></a><h1>Website Analytics</h1><p>Performa katalog dan perjalanan pembelian.</p></div><button className="an-button" onClick={()=>setRefresh(v=>v+1)} disabled={busy}>{busy?'Memuat…':'Perbarui data'}</button></header>
 <section className="an-filters" aria-label="Rentang tanggal"><div className="an-presets">{[['today','Today'],['7d','7 Days'],['30d','30 Days'],['custom','Custom Date Range']].map(([value,label])=><button key={value} aria-pressed={range===value} onClick={()=>setRange(value)}>{label}</button>)}</div>{range==='custom'&&<form onSubmit={e=>{e.preventDefault();setApplied(new URLSearchParams({start,end}).toString())}}><label>Dari<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Sampai<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="an-button" disabled={busy}>Terapkan</button></form>}<p className="an-muted">{data?`${date(data.range.start)} – ${date(data.range.end-1)} · WIB`:'Waktu Indonesia Barat (WIB)'}</p></section>
 <nav className="an-tabs" aria-label="Analytics tabs">{['Overview','Products','Search','Traffic'].map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {error&&<p className="an-error" role="alert">{error}</p>}{busy&&<p className="an-muted" role="status">Memuat data terbaru…</p>}
 {!data&&!busy&&!error&&<p className="an-muted">Pilih rentang tanggal untuk melihat data.</p>}
 {data&&<div aria-busy={busy}>
 {tab==='Overview'&&<><div className="an-kpis">{[
  ['Unique Visitors',number(k!.visitors),'Pengunjung unik dalam periode'],['Completed Orders',number(k!.completedOrders),'Pembayaran dikonfirmasi pemilik'],['Website Conversion Rate',pct(k!.conversion),'Completed orders ÷ unique visitors'],['Website Revenue',money(k!.revenue),'Total final pesanan, termasuk ongkir'],['Add to Cart Rate',pct(k!.addRate),'Pengunjung menambah ÷ melihat produk'],['Biggest Funnel Drop',k!.biggestDrop?pct(k!.biggestDrop.percent):'—',k!.biggestDrop?.label||'Belum cukup data']
 ].map(([label,value,help])=><section className="an-kpi" key={label}><h2>{label}</h2><p>{value}</p><small>{help}</small></section>)}</div>
 <section className="an-panel"><h2>Conversion Funnel</h2><p className="an-muted">Pengunjung unik per tahap. Satu pengunjung dihitung satu kali pada setiap tahap dalam periode.</p><div className="an-scroll"><table className="an-table an-funnel"><thead><tr><th>Tahap</th><th>Pengunjung</th><th>Conversion</th><th>Drop-off</th><th aria-label="Volume relatif"/></tr></thead><tbody>{data.funnel.map(f=><tr key={f.key}><th>{f.label}</th><td>{number(f.count)}</td><td>{pct(f.conversion)}</td><td>{pct(f.drop)}</td><td><div className="an-bar"><span style={{width:Math.min(100,data.kpis.visitors?f.count/data.kpis.visitors*100:0)+'%'}}/></div></td></tr>)}</tbody></table></div><p className="an-muted an-note">Conversion memakai tahap sebelumnya. Ini aktivitas pada rentang tanggal, sehingga pembayaran dari kunjungan sebelumnya bisa masuk periode ini. Completed Orders di KPI menghitung pesanan; funnel menghitung pengunjung.</p></section>
 <section className="an-panel an-status"><h2>System Status / Error Log</h2>{!data.errors.length?<p className="an-operational">All systems operational</p>:<><p className="an-muted">Kendala yang tercatat pada rentang ini; bukan pemeriksaan kesehatan real-time.</p><div className="an-scroll"><table className="an-table"><thead><tr><th>Kendala</th><th>Jumlah</th><th>Terakhir</th></tr></thead><tbody>{data.errors.map((e:any)=><tr key={e.code}><td>{ERROR_LABELS[e.code]||e.code}</td><td>{number(e.count)}</td><td>{date(e.lastSeen)}</td></tr>)}</tbody></table></div></>}</section></>}
 {tab==='Products'&&<><div className="an-boards"><ProductBoard title="Most Viewed" rows={data.leaderboards.viewed} metric="views"/><ProductBoard title="Most Added to Cart" rows={data.leaderboards.added} metric="adds"/><ProductBoard title="High Interest — Still Available" rows={data.leaderboards.interest} metric="adds"/></div><section className="an-panel"><h2>Product Performance</h2><p className="an-muted">Views: satu kali per produk per sesi. Adds: tindakan berhasil. Checkout dan completed: jumlah checkout/pesanan yang memuat produk.</p><div className="an-scroll"><table className="an-table an-products"><thead><tr>{['Produk / ID','Status','Views','Adds','ATC Rate','Checkout','Completed','Date Listed','Sold At'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.products.map(p=><tr key={p.id}><td><a href={'/produk/'+p.id}>{p.name}</a><small>{p.shortcode||p.id}</small></td><td><span className="an-pill">{p.status}</span></td><td>{number(p.views)}</td><td>{number(p.adds)}</td><td>{pct(p.addRate)}</td><td>{number(p.checkouts)}</td><td>{number(p.completed)}</td><td>{date(p.listedAt)}</td><td>{date(p.soldAt)}</td></tr>)}</tbody></table></div></section></>}
 {tab==='Search'&&<div className="an-search-grid">{[['Top Searches',data.search],['Zero Result Searches',data.zeroSearch]].map(([title,rows])=><section className="an-panel" key={String(title)}><h2>{String(title)}</h2>{!(rows as any[]).length?<p className="an-muted">Belum ada pencarian dalam periode ini.</p>:<div className="an-scroll"><table className="an-table"><thead><tr><th>Search Query</th><th>Count</th><th>{title==='Top Searches'?'Avg. Results':'Results'}</th><th>Last Searched</th></tr></thead><tbody>{(rows as any[]).map(r=><tr key={r.query}><td>{r.query}</td><td>{number(r.count)}</td><td>{r.results}</td><td>{date(r.lastSearched)}</td></tr>)}</tbody></table></div>}</section>)}</div>}
 {tab==='Traffic'&&<section className="an-panel"><h2>Traffic Sources</h2><p className="an-muted">Atribusi sumber sesi saat checkout dimulai. UTM diutamakan, lalu referrer. Sesi baru setelah 30 menit tanpa aktivitas.</p><div className="an-scroll"><table className="an-table"><thead><tr><th>Source</th><th>Visitors</th><th>Completed Orders</th><th>Conversion Rate</th><th>Revenue</th></tr></thead><tbody>{data.traffic.map(r=><tr key={r.source}><td>{r.source}</td><td>{number(r.visitors)}</td><td>{number(r.orders)}</td><td>{pct(r.conversion)}</td><td>{money(r.revenue)}</td></tr>)}</tbody></table></div><p className="an-muted an-note">Pengunjung yang datang lewat beberapa channel dapat dihitung pada masing-masing channel. Pesanan tanpa sesi tercatat masuk Other.</p></section>}
 <p className="an-muted an-footnote">Pencatatan aktif sejak {date(data.startedAt)}. Data sebelum aktivasi tidak direkonstruksi. Pencarian dan aktivitas browser dapat tidak tercatat jika diblokir browser atau koneksi terputus.</p>
 </div>}</main>;
}
