"use client";
import { useEffect,useState,type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Truck,Check,RefreshCw } from "lucide-react";
import { defaultShippingConfig,shipmentLabels,type ShippingConfig,type KomshipLocation,type ShipmentSummary } from "@/modules/order/fulfilment-types";
import { rupiah,type Order } from "@/modules/order/order-types";
import { jntInsuranceQuote,JNT_INSURANCE_MINIMUM } from "@/modules/order/shipping-insurance";
import { kiriminInsuranceEstimate as insuranceEstimate } from "@/modules/order/shipping-insurance";
type SettingsData={config:ShippingConfig;hasKey:boolean;hasPin:boolean;ratesReady:boolean;bookingReady:boolean;kiriminWebhookActive:boolean;webhookActive:boolean;telegramReady:boolean};
async function request<T>(path:string,body?:unknown){const r=await fetch(path,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:undefined);const data=await r.json() as T&{error?:string};if(!r.ok||data.error)throw new Error(data.error||"Permintaan belum berhasil.");return data as T;}
export function ShippingSettings(){const [c,setC]=useState<ShippingConfig>({...defaultShippingConfig}),[data,setData]=useState<SettingsData|null>(null),[key,setKey]=useState(""),[pin,setPin]=useState(""),[locations,setLocations]=useState<KomshipLocation[]>([]),[error,setError]=useState(""),[info,setInfo]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{request<SettingsData>("/api/admin/order/shipping").then(d=>{setData(d);setC(d.config);}).catch(e=>setError(e.message));},[]);
 const change=<K extends keyof ShippingConfig>(field:K,value:ShippingConfig[K])=>setC(prev=>({...prev,[field]:value}));
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setInfo("");try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e?:FormEvent){e?.preventDefault();await run(async()=>{const d=await request<SettingsData>("/api/admin/order/shipping",{action:"save",config:c,key,pin});setData(d);setC(d.config);setKey("");setPin("");setInfo("Pengaturan pengiriman disimpan.");});}
 return <section className="panel shipping-settings"><div className="section-title"><span className="iconbox"><Truck size={20}/></span><div><h2>03 · Pengiriman J&T · KiriminAja</h2><p>Booking setelah konfirmasi pembayaran di Telegram.</p></div></div>
 {error&&<div role="alert" className="notice error">{error}</div>}{info&&<div role="status" className="notice success">{info}</div>}
 <div className="notice setup">{data?.ratesReady?"Ongkir pelanggan memakai KiriminAja. ":"Ongkir sebelumnya tetap aktif sampai API produksi dan wilayah KiriminAja siap. "}{data?.hasKey?"API key tersimpan. ":"API key KiriminAja belum diisi. "}{data?.hasPin?"PIN KA Credit tersimpan.":"PIN KA Credit belum diisi."} Menyimpan pengaturan tidak membuat booking.</div>
 <details className="activation-guide"><summary>Cara mengaktifkan booking nyata</summary><ol><li>Ajukan akses API Basic melalui <a href="https://kiriminaja.com/integration" target="_blank" rel="noreferrer">KiriminAja</a>. Gunakan key sandbox untuk UAT, lalu minta key produksi serta akses cetak label PDF.</li><li>Aktifkan dan isi saldo KA Credit di <a href="https://app.kiriminaja.com" target="_blank" rel="noreferrer">dashboard KiriminAja</a>. Siapkan PIN KA Credit 6 digit. Saldo digunakan untuk ongkir dan asuransi. Minta KiriminAja memverifikasi akses saldo/PIN otomatis dan label pada UAT akun Anda; pemeriksaan KA Credit API masih berstatus beta.</li><li>Pilih lingkungan, isi API key dan PIN, simpan dahulu, lalu cari wilayah asal 40375. Pilih kelurahan/desa pengirim yang benar dan lengkapi berat, ukuran, serta jadwal pickup sebelum 16.00 WIB.</li><li>Setelah UAT dan aktivasi produksi disetujui KiriminAja, hubungkan callback KiriminAja, lalu aktifkan konfirmasi Telegram dan booking. Setiap booking nyata tetap menunggu tombol konfirmasi pemilik pada invoice.</li></ol></details>
 <div className="notice setup"><b>Asuransi J&T wajib.</b> Nilai barang sesuai invoice. Premi mengikuti respons KiriminAja; estimasi 0,2% dibulatkan ke atas per Rp100, ditanggung toko. Booking ditahan jika layanan tidak menyediakan asuransi atau saldo tidak cukup.</div>
 <form onSubmit={save}><div className="fields-two"><label>Lingkungan API<select value={c.environment} onChange={e=>{change("environment",e.target.value as ShippingConfig["environment"]);change("enabled",false);change("origin",null);}}><option value="production">Produksi · pesanan nyata</option><option value="sandbox">Sandbox · uji tanpa pengiriman</option></select></label><label>API key KiriminAja<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={data?.hasKey?"Isi hanya untuk mengganti key":"API key sesuai lingkungan"}/></label></div>
 <label>PIN KA Credit<input type="password" inputMode="numeric" autoComplete="new-password" value={pin} maxLength={6} onChange={e=>setPin(e.target.value)} placeholder={data?.hasPin?"Isi hanya untuk mengganti PIN":"PIN KA Credit 6 digit"}/></label>
 <div className="fields-two"><label>Nama pengirim<input value={c.senderName} onChange={e=>change("senderName",e.target.value)} required maxLength={100}/></label><label>No. HP pengirim<input value={c.senderPhone} onChange={e=>change("senderPhone",e.target.value)} required inputMode="tel"/></label></div>
 <label>Alamat pengirim<textarea value={c.senderAddress} onChange={e=>change("senderAddress",e.target.value)} required rows={2}/></label>
 <div className="fields-two"><label>Kode pos asal<input value="40375" readOnly/></label><label>Email pengirim (opsional)<input type="email" value={c.senderEmail} onChange={e=>change("senderEmail",e.target.value)} placeholder="Email akun pengiriman"/></label></div>
 <label>Wilayah asal KiriminAja<input readOnly value={c.origin?.label||"Belum dipilih · Baleendah, Kabupaten Bandung, 40375"}/></label><Button type="button" className="secondary" disabled={busy||!data?.hasKey} onClick={()=>run(async()=>{const r=await request<{locations:KomshipLocation[]}>("/api/admin/order/shipping",{action:"search",query:"40375"});setLocations(r.locations);})}>Cari wilayah asal</Button>
 {locations.length>0&&<label className="origin-picker">Pilih kelurahan/desa pengirim<select value={c.origin?.id||""} onChange={e=>change("origin",locations.find(l=>l.id===Number(e.target.value))||null)}><option value="">Pilih wilayah yang sesuai alamat</option>{locations.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label>}
 <div className="fields-two package-fields"><label>Berat default (gram)<input type="number" min={100} max={30000} step={1} value={c.defaultGrams} onChange={e=>change("defaultGrams",Number(e.target.value))}/></label><label>Ukuran kertas untuk cetak<select value={c.labelPage} onChange={e=>change("labelPage",e.target.value as ShippingConfig["labelPage"])}><option value="page_6">Thermal 10 × 15 cm</option><option value="page_5">Thermal 10 × 10 cm</option><option value="page_1">A4 · satu label</option></select></label></div>
 <div className="dimensions">{(["length","width","height"] as const).map((field,i)=><label key={field}>{["Panjang","Lebar","Tinggi"][i]} (cm)<input type="number" min={0} max={150} step="0.1" value={c[field]} onChange={e=>change(field,Number(e.target.value))}/></label>)}</div><p className="field-help">Isi ukuran paket yang sebenarnya. Berat pesanan mengikuti berat pada invoice; dapat disesuaikan sebelum konfirmasi.</p>
 <div className="fields-two package-fields"><label>Jam pickup (WIB)<input type="time" value={c.pickupTime} onChange={e=>change("pickupTime",e.target.value)}/></label><label>Hari pickup<select value={c.pickupDay} onChange={e=>change("pickupDay",e.target.value as ShippingConfig["pickupDay"])}><option value="same_or_next">Hari ini, atau besok jika jam lewat</option><option value="next_day">Selalu besok</option></select></label></div>
 <details><summary>Titik pickup jika diwajibkan layanan</summary><div className="fields-two"><label>Latitude pengirim<input type="number" step="any" value={c.senderLatitude??""} onChange={e=>change("senderLatitude",e.target.value?Number(e.target.value):null)}/></label><label>Longitude pengirim<input type="number" step="any" value={c.senderLongitude??""} onChange={e=>change("senderLongitude",e.target.value?Number(e.target.value):null)}/></label></div><p className="field-help">Gunakan titik alamat pengirim yang sebenarnya. Layanan yang mewajibkan geolokasi ditahan sampai titik pengirim dan penerima lengkap.</p></details>
 <p className="field-help">Potongan pickup terbesar yang tersedia dalam respons tarif dipilih untuk layanan yang sama. Voucher akun yang perlu diklaim di dashboard belum memiliki API penukaran yang terdokumentasi. Ukuran cetak mengatur kertas printer; PDF tetap label asli dari penyedia.</p>
 <label className="shipping-checkbox"><input type="checkbox" checked={c.enabled} onChange={e=>change("enabled",e.target.checked)}/>Aktifkan booking setelah saya mengonfirmasi di Telegram</label>
 <Button className="primary" disabled={busy}>Simpan pengaturan<Check size={16}/></Button>
 </form><div className="webhook-status"><b>Konfirmasi Telegram: {data?.webhookActive?"aktif":"perlu diaktifkan"}</b><Button className="secondary" disabled={busy||!data?.telegramReady} onClick={()=>run(async()=>{const d=await request<SettingsData>("/api/admin/order/shipping",{action:"webhook"});setData(d);setInfo("Tombol konfirmasi Telegram siap digunakan.");})}>Aktifkan / periksa konfirmasi</Button></div>
 <div className="webhook-status"><b>Callback resi KiriminAja: {data?.kiriminWebhookActive?"aktif":"belum terhubung"}</b><Button className="secondary" disabled={busy||!data?.hasKey} onClick={()=>run(async()=>{const d=await request<SettingsData>("/api/admin/order/shipping",{action:"kirimin-webhook"});setData(d);setInfo("Callback KiriminAja terhubung. Resi dan label yang terbit kemudian akan dilanjutkan otomatis.");})}>Hubungkan callback ke aplikasi ini</Button><p className="field-help">KiriminAja menyediakan satu callback per akun. Tombol ini mengganti callback akun tersebut ke ELITE.VTG. Tombol cek ulang Telegram tetap tersedia bila callback terlambat.</p></div>
 <p className="fine-print"><a href="https://app.kiriminaja.com" target="_blank" rel="noreferrer">Buka akun KiriminAja</a> untuk aktivasi API dan isi KA Credit.</p></section>;
}
 export function OrderShipping({order:o,refresh}:{order:Order&{shipment?:ShipmentSummary|null;payment_state?:string};refresh:()=>Promise<void>}){const legacy=o.shipment?.provider==="komship",provider=legacy?"Komship":"KiriminAja",insurance=legacy?jntInsuranceQuote(o.item_amount||0):insuranceEstimate(o.item_amount||0);const [grams,setGrams]=useState(o.shipment?.weight_grams||o.quote?.grams||1000),[max,setMax]=useState(o.shipment?.max_cost??((o.shipping_amount||0)+Math.ceil(insurance.premium))),[no,setNo]=useState(legacy?"":o.id),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState(""),[locationId,setLocationId]=useState(""),[locations,setLocations]=useState<KomshipLocation[]>([]),[error,setError]=useState(""),[info,setInfo]=useState(""),[busy,setBusy]=useState(false),[trackingUrl,setTrackingUrl]=useState("");
 async function act(action:string,extra:Record<string,unknown>={}){setBusy(true);setError("");setInfo("");try{await request("/api/admin/order/shipments/"+o.id,{action,...extra});setInfo(action==="package"?"Berat dan batas biaya disimpan.":"Pengiriman diperbarui.");await refresh();}catch(e){setError((e as Error).message);await refresh();}finally{setBusy(false);}}
 const s=o.shipment,locked=!!s?.provider_no||s?.state==="booking_unknown"||s?.state==="booking_processing";
 return <div className="order-shipping"><p><b>Pembayaran: {o.payment_state==="payment_confirmed"?"dikonfirmasi pemilik":"bukti diterima"}</b>{s&&<> · {shipmentLabels[s.state]||s.state}</>}</p>{s?.awb&&<p><b>Resi J&T: {s.awb}</b> · Paket belum dianggap sudah dikirim.</p>}{s?.last_error&&<div className="notice error">{s.last_error}</div>}
 <p><b>Asuransi wajib:</b> {s?.insurance_state==="verified"?<>Nilai barang yang diajukan {rupiah(s.insured_value!)} · premi {rupiah(s.insurance_fee!)} terverifikasi pada {provider}.</>:insurance.eligible?<>Nilai barang {rupiah(insurance.declaredValue)} · estimasi premi {rupiah(insurance.premium)}. Menunggu verifikasi pada booking.</>:<>Nilai barang belum valid{legacy?` atau di bawah minimum ${rupiah(JNT_INSURANCE_MINIMUM)}`:""}. Booking ditahan; periksa asuransi dengan {provider}.</>} Premi ditanggung toko.</p>
 {error&&<div role="alert" className="notice error">{error}</div>}{info&&<div role="status" className="notice success">{info}</div>}
 {!locked&&<details><summary>Berat paket & batas biaya booking</summary><div className="fields-two"><label>Berat (gram)<input type="number" value={grams} min={100} max={30000} onChange={e=>setGrams(Number(e.target.value))}/></label><label>Batas biaya ongkir + asuransi (Rp)<input type="number" value={max} min={0} max={2000000} onChange={e=>setMax(Number(e.target.value))}/></label></div><Button className="secondary" disabled={busy} onClick={()=>act("package",{grams,maxCost:max,...(locationId?{destinationId:Number(locationId)}:{}),...(latitude&&longitude?{latitude:Number(latitude),longitude:Number(longitude)}:{})})}>Simpan berat & batas biaya</Button><Button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError("");try{const r=await request<{locations:KomshipLocation[]}>("/api/admin/order/shipping",{action:"search",query:o.postcode});setLocations(r.locations);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Periksa wilayah KiriminAja</Button>{locations.length>0&&<label>Wilayah tujuan sesuai invoice<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Pilih wilayah</option>{locations.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label>}<div className="fields-two"><label>Latitude penerima (jika diwajibkan)<input type="number" step="any" value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label>Longitude penerima (jika diwajibkan)<input type="number" step="any" value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div><p className="field-help">Perubahan ini khusus biaya pengiriman toko; total pembayaran pada invoice pelanggan tetap.</p></details>}
 {o.payment_state!=="payment_confirmed"&&<Button className="secondary" disabled={busy} onClick={()=>act("confirmation-button")}>Pasang tombol konfirmasi di Telegram</Button>}
 {s?.state==="booking_unknown"&&<details><summary>Hubungkan booking yang sudah ada</summary><label>Nomor booking/invoice dari dashboard {provider}<input value={no} onChange={e=>setNo(e.target.value)} placeholder={legacy?"KOM…":o.id}/></label><Button className="secondary" disabled={busy||!no} onClick={()=>act("reconcile",{providerNo:no})}>Periksa & hubungkan booking</Button><p className="field-help">Data penerima diperiksa sebelum booking digunakan. Booking baru tetap ditahan.</p></details>}
 {o.payment_state==="payment_confirmed"&&<div className="action-row"><Button className="secondary" disabled={busy} onClick={()=>act("retry")}><RefreshCw size={15}/>Coba ulang / cek resi & label</Button>{legacy&&s?.provider_no&&["pending","failed"].includes(s.pickup_state)&&<Button className="secondary" disabled={busy} onClick={()=>act("pickup")}>Gunakan jadwal pickup terbaru</Button>}</div>}
 {(s?.pdfReady||s?.pngReady)&&<div className="action-row">{s.pdfReady&&s.pngReady&&<a className="primary link-button" href={"/admin/order/print/"+o.id}>Buka label & cetak</a>}{s.pdfReady&&<a className="secondary link-button" href={"/api/admin/order/shipments/"+o.id+"?format=pdf"}>Unduh PDF resmi</a>}{s.pngReady&&<a className="secondary link-button" href={"/api/admin/order/shipments/"+o.id+"?format=png"}>Unduh PNG label</a>}</div>}
 <Button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError("");try{const r=await request<{accessUrl:string}>("/api/admin/order/tracking/"+o.id);setTrackingUrl(r.accessUrl);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Tautan pelacakan pembeli</Button>{trackingUrl&&<p className="field-help"><a href={trackingUrl} target="_blank" rel="noreferrer">{trackingUrl}</a><br/>Salin tautan ini untuk pembeli yang bersangkutan.</p>}</div>;
}
