"use client";
/* eslint-disable @next/next/no-img-element -- Print the image rendered from the original carrier PDF. */
import { BrandLogo } from "@/components/brand-logo";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { Printer,Share2,Download } from "lucide-react";
type Label={invoice:string;awb:string;buyer:string;size:{width:number;height:number;label:string};pdfUrl:string;pngUrl:string};
export function LabelPrint({label}:{label:Label}){const [files,setFiles]=useState<{pdf:File;png:File}|null>(null),[ready,setReady]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;Promise.all([fetch(label.pdfUrl,{cache:"no-store"}),fetch(label.pngUrl,{cache:"no-store"})]).then(async ([pdf,png])=>{if(!pdf.ok||!png.ok)throw new Error();const blobs=await Promise.all([pdf.blob(),png.blob()]);if(active)setFiles({pdf:new File([blobs[0]],"ELITE-"+label.awb+".pdf",{type:"application/pdf"}),png:new File([blobs[1]],"ELITE-"+label.awb+".png",{type:"image/png"})});}).catch(()=>{if(active)setError("File belum dapat dimuat. Muat ulang halaman.");});return()=>{active=false;};},[label.awb,label.pdfUrl,label.pngUrl]);
 async function share(format:"pdf"|"png"){setError("");const file=files?.[format];if(!file)return;try{if(!navigator.canShare?.({files:[file]})){setError("Bagikan file belum didukung browser ini. Unduh label lalu buka di aplikasi printer.");return;}await navigator.share({files:[file],title:"Label ELITE.VTG · "+label.awb});}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setError("File belum dapat dibagikan. Unduh label lalu buka di aplikasi printer.");}}
 return <><div className="print-controls"><header className="site-header"><Link href="/admin/order" className="brand"><BrandLogo/><small>LABEL PENGIRIMAN</small></Link><Link href="/admin/order" className="text-link">Dashboard</Link></header><main className="shell print-intro"><h1>Cetak label resmi.</h1><p>{label.buyer} · {label.awb}<br/>{label.invoice} · Kertas {label.size.label}</p><div className="action-row"><Button className="primary" disabled={!ready} onClick={()=>window.print()}><Printer size={18}/>Cetak label</Button><a className="secondary link-button" href={label.pdfUrl}><Download size={16}/>PDF asli</a><a className="secondary link-button" href={label.pngUrl}><Download size={16}/>PNG label</a></div><div className="action-row print-share"><Button className="secondary" disabled={!files} onClick={()=>void share("png")}><Share2 size={16}/>Bagikan PNG ke aplikasi printer</Button><Button className="secondary" disabled={!files} onClick={()=>void share("pdf")}>Bagikan PDF</Button></div><p className="field-help">Untuk printer Bluetooth di HP, buka label melalui aplikasi printer yang mendukung model Anda. Pilih ukuran kertas {label.size.label} dan satu salinan. Tombol Cetak membuka pilihan printer pada perangkat.</p>{error&&<p className="notice error" role="alert">{error}</p>}</main></div>
 <div className="print-sheet" style={{width:label.size.width+"mm",minHeight:label.size.height+"mm"}}><img src={label.pngUrl} alt={"Label resmi untuk "+label.buyer} onLoad={()=>setReady(true)} onError={()=>setError("Gambar label belum dapat dimuat.")}/></div><style>{`@media print{@page{size:${label.size.width}mm ${label.size.height}mm;margin:0}html,body{margin:0!important;padding:0!important;background:white!important}.print-controls{display:none!important}.print-sheet{margin:0!important;padding:0!important;border:0!important;box-shadow:none!important;width:${label.size.width}mm!important;min-height:0!important;height:${label.size.height}mm!important;break-inside:avoid}.print-sheet img{display:block;width:100%!important;height:100%!important;object-fit:contain!important}}`}</style></>;
}
