import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import fs from 'node:fs/promises';
await fs.mkdir('.test-runtime',{recursive:true});
const bundle=await build({stdin:{contents:"export * from './modules/catalog/caption-parser';export * from './modules/catalog/catalog-types';export * from './modules/catalog/taxonomy';",resolveDir:process.cwd(),loader:'ts'},bundle:true,format:'esm',platform:'node',write:false});
await fs.writeFile('.test-runtime/domain.mjs',bundle.outputFiles[0].contents);
const {parseCaption,normalizeInstagramUrl,parseFit,matchesProduct,totalStock,DEFAULT_FEATURES,normalizeSearch,suggestTaxonomy,QUICK_FILTERS}=await import(pathToFileURL(process.cwd()+'/.test-runtime/domain.mjs'));
const caption=`Nama: PRL Cotton Poplin Shirt — White
Harga: IDR 365.000
Kondisi: Very good condition.
Minus: –
Stok 1: 3 pcs, Fit S–M, panjang 72 cm, lebar 50 cm.
Stok 2: 2 pcs, Fit L, panjang 78 cm, lebar 58 cm.
Informasi tambahan: Shopee +17% admin.`;
let count=0;function check(name,fn){fn();count++;console.log('PASS '+name)}
const result=parseCaption(caption);
check('Contoh caption: satu produk, dua kelompok, total lima unit',()=>{assert.equal(result.name,'PRL Cotton Poplin Shirt — White');assert.equal(result.price,365000);assert.equal(result.condition,'Very good condition.');assert.equal(result.defects,'–');assert.equal(result.groups.length,2);assert.equal(result.groups.reduce((s,g)=>s+g.qty,0),5);assert.deepEqual(result.groups[0].fits,['S','M']);assert.equal(result.groups[0].label,'Fit S–M');assert.equal(result.groups[0].lengthCm,72);assert.equal(result.groups[0].widthCm,50);assert.deepEqual(result.groups[1].fits,['L']);assert.equal(result.groups[1].label,'Fit L');assert.equal(result.groups[1].lengthCm,78);assert.equal(result.groups[1].widthCm,58)});
check('Satu barang satu fit tidak ditebak jumlahnya',()=>{const p=parseCaption('PRL Crewneck — Navy\nIDR 300.000\nGood condition\nMinus: –\nFit M\nPanjang 70 cm, lebar 52 cm');assert.equal(p.groups.length,1);assert.deepEqual(p.groups[0].fits,['M']);assert.equal(p.groups[0].qty,null);assert.ok(p.warnings.some(w=>w.includes('jumlah stok')))});
check('Stok lebih dari satu tidak digandakan oleh rentang fit',()=>{assert.deepEqual(parseFit('S–L'),['S','M','L']);const p=parseCaption('PRL Hoodie — Black\nHarga: Rp425.000\nStok 1: 4 pcs, Fit M–L, panjang 72 cm, lebar 58 cm');assert.equal(p.groups.length,1);assert.equal(p.groups[0].qty,4);assert.deepEqual(p.groups[0].fits,['M','L'])});
check('Size tag berbeda dari fit',()=>{const p=parseCaption('PRL Shirt — White\nIDR 365.000\nSize tag XL\nFit M\n1 pcs\nPanjang 72 cm, lebar 53 cm');assert.equal(p.groups[0].tagSize,'XL');const tagOnly=parseCaption('PRL Shirt — White\nIDR 365.000\nSize tag XL\n1 pcs');assert.equal(tagOnly.groups[0].tagSize,'XL');assert.deepEqual(tagOnly.groups[0].fits,[])});
check('Harga/condition khusus kelompok tetap terpisah',()=>{const p=parseCaption('Nama: PRL Shirt — White\nKondisi: Good condition\nMinus: –\nStok 1: 2 pcs, Fit M, panjang 70 cm, lebar 52 cm, IDR 300.000, Kondisi: Good condition\nStok 2: 1 pcs, Fit L, panjang 76 cm, lebar 58 cm, IDR 350.000, Kondisi: Very good condition');assert.equal(p.price,null);assert.equal(p.groups[0].price,300000);assert.equal(p.groups[1].price,350000);assert.equal(p.groups[1].condition,'Very good condition')});
check('Caption ambigu tidak menebak harga, stok, kondisi, atau minus',()=>{const p=parseCaption('PRL Shirt — White\nHarga: Rp300.000 / Rp350.000\nStok 1: 2–3 pcs, Fit S–M\nUkuran menyusul');assert.equal(p.price,null);assert.equal(p.groups[0].qty,null);assert.equal(p.groups[0].lengthCm,null);assert.equal(p.condition,null);assert.equal(p.defects,null);assert.ok(p.warnings.length>3)});
check('Shopee +17% tidak menambah harga katalog',()=>{assert.equal(result.price,365000);const p=parseCaption('PRL Shirt — White\nHarga: Rp365.000\nShopee Rp427.050 admin 17%\nStok 1: 1 pcs, Fit M');assert.equal(p.price,365000)});
check('Tracking dinormalisasi dan identitas postingan tetap',()=>{assert.deepEqual(normalizeInstagramUrl('https://www.instagram.com/p/DeHNub0mMa2/?utm_source=ig_web_copy_link&stkn=abc'),{shortcode:'DeHNub0mMa2',url:'https://www.instagram.com/p/DeHNub0mMa2/'});assert.equal(normalizeInstagramUrl('https://instagram.com/reel/DeHNub0mMa2/').shortcode,'DeHNub0mMa2');assert.throws(()=>normalizeInstagramUrl('https://instagram.com.evil.test/p/DeHNub0mMa2/'));assert.throws(()=>normalizeInstagramUrl('https://www.instagram.com/elite.vtg/'))});
const p={...result,id:'p',status:'published',groups:result.groups};
check('L habis: filter L hilang, S/M masih tersedia',()=>{p.groups[1].qty=0;assert.equal(matchesProduct(p,{size:'L'}),false);assert.equal(matchesProduct(p,{size:'S'}),true);assert.equal(matchesProduct(p,{size:'M'}),true);assert.equal(totalStock(p),3)});
check('Semua stok habis dan draf tidak terlihat publik',()=>{p.groups[0].qty=0;assert.equal(matchesProduct(p,{}),false);p.groups[0].qty=3;p.status='draft';assert.equal(matchesProduct(p,{}),false);p.status='published'});
check('Filter harga/size menggunakan kelompok yang sama',()=>{p.groups[0].price=365000;p.groups[1].price=250000;p.groups[1].qty=1;assert.equal(matchesProduct(p,{size:'M',max:'300000'}),false);assert.equal(matchesProduct(p,{size:'L',max:'300000'}),true)});
check('Kondisi dan minus yang saling bertentangan tidak ditebak',()=>{const p=parseCaption('PRL Shirt — White\nIDR 365.000\nKondisi: Good condition\nCondition: Very good condition\nMinus: –\nMinus: noda\nStok 1: 1 pcs, Fit M');assert.equal(p.condition,null);assert.equal(p.defects,null)});
check('Ukuran tanpa cm atau saling bertentangan ditandai',()=>{const p=parseCaption('PRL Shirt — White\nStok 1: 1 pcs, Fit M\nPanjang 72\nLebar 50');assert.equal(p.groups[0].lengthCm,null);assert.equal(p.groups[0].widthCm,null);const conflict=parseCaption('PRL Shirt — White\nStok 1: 1 pcs, Fit M, panjang 72 cm, panjang 74 cm, lebar 50 cm');assert.equal(conflict.groups[0].lengthCm,null);assert.equal(conflict.groups[0].widthCm,50)});
check('Contoh klasifikasi memakai jenis barang; bukaan dan kerah tetap ciri',()=>{for(const [name,category,features] of [['Cable Knit Quarter Zip','Sweater & Knitwear',['quarter-zip','cable-knit']],['Knit Crewneck','Sweater & Knitwear',['crewneck']],['Quarter Zip berbahan sweatshirt','Sweatshirt & Hoodie',['quarter-zip']],['Polo Long Sleeve','Polo',['long-sleeve']],['Hoodie sweatshirt','Sweatshirt & Hoodie',['hoodie']]]){const parsed=parseCaption('Nama: '+name);assert.equal(parsed.name,name);assert.equal(parsed.category,category);assert.deepEqual(parsed.features,features)}for(const name of ['Quarter Zip','Half Button','Crewneck']){const parsed=parseCaption('Nama: '+name);assert.equal(parsed.category,'');assert.ok(parsed.warnings.some(w=>w.includes('Kategori utama')))}});
check('Halfzip dan Quarterzip dinormalisasi tetapi dua jenis zip tetap berbeda',()=>{assert.equal(normalizeSearch('Halfzip'),'half zip');assert.equal(normalizeSearch('Quarterzip'),'quarter zip');assert.notEqual(normalizeSearch('Halfzip'),normalizeSearch('Quarterzip'));assert.equal(normalizeSearch('Crew Neck'),'crewneck')});
const multi={...result,id:'multi',name:'PRL Cable Knit Quarter Zip',category:'Sweater & Knitwear',features:['quarter-zip','cable-knit'],status:'published',groups:[{...result.groups[0],qty:3,price:null},{...result.groups[1],qty:0,price:null}]};
const sweatshirt={...multi,id:'sweat',name:'PRL Fleece Quarterzip',category:'Sweatshirt & Hoodie',features:['quarter-zip']};
check('Pencarian mencakup nama, kategori, ciri dan variasi ejaan',()=>{for(const q of ['Quarterzip','Quarter Zip','Cableknit','Sweater','Knitwear'])assert.equal(matchesProduct(multi,{q}),true,q);assert.equal(matchesProduct(multi,{q:'Halfzip'}),false);assert.equal(matchesProduct({...multi,name:'PRL Sweater'},{q:'Quarterzip'}),true)});
check('Pilihan cepat Quarter Zip lintas kategori tidak menggandakan kartu atau stok',()=>{const quick=QUICK_FILTERS.find(q=>q.id==='quarter-zip');const list=[multi,sweatshirt];const found=list.filter(p=>matchesProduct(p,{features:quick.features}));assert.deepEqual(found.map(p=>p.id),['multi','sweat']);assert.equal(totalStock(found[0]),3);assert.equal(new Set(found.map(p=>p.id)).size,2)});
check('Ciri berbeda kelompok AND; pilihan satu kelompok OR',()=>{assert.equal(matchesProduct(multi,{features:['quarter-zip','cable-knit']}),true);assert.equal(matchesProduct(sweatshirt,{features:['quarter-zip','cable-knit']}),false);assert.equal(matchesProduct(multi,{features:['quarter-zip','half-zip']}),true);assert.equal(matchesProduct(multi,{features:['half-zip','cable-knit']}),false)});
check('Kategori, ciri, size, brand dan harga dapat digabung; L habis tetap ditolak',()=>{assert.equal(matchesProduct(multi,{category:['Sweater & Knitwear','Polo'],features:['cable-knit','quarter-zip'],size:['S','M'],brand:['Burberry','PRL'],min:'350000',max:'400000'}),true);assert.equal(matchesProduct(multi,{features:['quarter-zip'],size:'L'}),false);assert.equal(matchesProduct(multi,{category:'Polo',features:['quarter-zip']}),false);assert.equal(matchesProduct(multi,{brand:'Burberry'}),false);assert.equal(matchesProduct(multi,{max:'300000'}),false)});
check('Quick Polo Long Sleeve membutuhkan kategori Polo sekaligus ciri Long Sleeve',()=>{const q=QUICK_FILTERS.find(q=>q.id==='polo-long-sleeve');assert.equal(matchesProduct({...multi,category:'Polo',features:['long-sleeve']},{category:q.category,features:q.features}),true);assert.equal(matchesProduct({...multi,features:['long-sleeve']},{category:q.category,features:q.features}),false)});
check('Barang lama belum dipetakan tetap ditemukan di Semua',()=>{const legacy={...multi,category:'',legacyCategory:'Lainnya'};assert.equal(matchesProduct(legacy,{}),true);assert.equal(matchesProduct(legacy,{category:'Sweater & Knitwear'}),false);assert.equal(matchesProduct(legacy,{q:'Quarterzip',size:'S'}),true)});
check('Ciri dan alias tambahan admin ikut pencarian dan filter',()=>{const terms=[...DEFAULT_FEATURES,{id:'custom-mock',label:'Mock Neck',groupId:'style',aliases:['Mockneck','High Collar']}];const product={...multi,features:['custom-mock'],name:'PRL Cotton Top'};assert.equal(matchesProduct(product,{q:'high collar'},terms),true);assert.equal(matchesProduct(product,{features:['custom-mock']},terms),true)});
console.log(`${count} pengujian domain lulus.`);
