import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync,realpathSync} from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const require=createRequire(import.meta.url);
const {build}=require('esbuild');
const result=await build({stdin:{contents:"export {CustomerSupport} from './components/customer-support';export {ProductCard} from './components/product-card';export {matchesProduct} from './modules/catalog/catalog-types';export {DEFAULT_FEATURES} from './modules/catalog/taxonomy';",resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',format:'esm',target:'node24',jsx:'automatic',external:['react','react/jsx-runtime'],banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},write:false});
mkdirSync('.test-runtime/tests',{recursive:true});const filename=path.resolve('.test-runtime/tests/product-card.mjs');writeFileSync(filename,result.outputFiles[0].contents);const {CustomerSupport,ProductCard,matchesProduct,DEFAULT_FEATURES}=await import(pathToFileURL(filename));
const p={id:'p',name:'PRL Cable Knit Quarter Zip',brand:'PRL',category:'Sweater & Knitwear',features:['quarter-zip','cable-knit'],instagramUrl:'https://www.instagram.com/p/DeHNub0mMa2/',photoKey:'photo',price:365000,status:'published',groups:[{id:'g',fits:['S','M'],tagSize:'XL',lengthCm:72,widthCm:50,qty:1}]};
const selected=[p].filter(p=>matchesProduct(p,{features:['quarter-zip','cable-knit'],category:'Sweater & Knitwear',size:'M'}));assert.equal(selected.length,1);
const props={features:DEFAULT_FEATURES,cart:[],cartCount:0,checkoutReady:true,onPick(){},onNavigate(){}};
const html=selected.map(product=>renderToStaticMarkup(createElement(ProductCard,{...props,product}))).join('');
assert.equal((html.match(/<article /g)||[]).length,1);assert.ok(html.includes('Size S / M'));assert.ok(!html.includes('Details size'));assert.ok(!html.includes('72 cm'));assert.ok(!html.includes('50 cm'));assert.ok(!html.includes('1 pcs'));
assert.match(html,/<a class="product-card-link" href="\/produk\/p"/);
assert.equal((html.match(/<a /g)||[]).length,1);
assert.ok(!html.includes('instagram.com'));assert.ok(!html.includes('Lihat di Instagram'));
const native=renderToStaticMarkup(createElement(ProductCard,{...props,product:{...p,instagramUrl:''}}));assert.match(native,/<a class="product-card-link" href="\/produk\/p"/);
const support=renderToStaticMarkup(createElement(CustomerSupport,{hasCart:true}));assert.match(support,/class="customer-support has-cart"/);assert.ok(support.includes('Got question? ask us on dm or Whatsapp'));assert.match(support,/href="https:\/\/wa.me\/6285174389305" target="_blank" rel="noopener noreferrer"/);assert.ok(!support.includes('fbclid'));assert.ok(support.includes('Kirim DM lewat profil @elite.vtg'));
const summary=support.match(/<summary[^>]*>([\s\S]*?)<\/summary>/)?.[1];assert.ok(summary);assert.ok(!summary.includes('Got question'));assert.match(support,/aria-label="Hubungi ELITE.VTG melalui DM atau WhatsApp"/);
console.log('PASS Satu kartu/stok S/M; semua tautan produk menuju detail toko, bantuan WhatsApp memakai nomor tepat tanpa tracking.');
