import test,{after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,mkdir,writeFile,rm,readFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
import {createClient} from '@libsql/client';
import {migrate} from '../scripts/migration-core.mjs';
const dir=await mkdtemp(path.join(os.tmpdir(),'elite-rewards-'));
Object.assign(process.env,{TURSO_DATABASE_URL:'file:'+path.join(dir,'test.db'),SITE_ORIGIN:'https://elite.test',CONFIG_SECRET:'a'.repeat(64),AUTH_SECRET:'b'.repeat(64),PAYMENT_BCA_ACCOUNT_NUMBER:'1234567890',PAYMENT_BCA_ACCOUNT_HOLDER:'SIMULATED OWNER',STORAGE_DRIVER:'local',LOCAL_STORAGE_PATH:path.join(dir,'files')});
delete process.env.VERCEL;delete process.env.TURSO_AUTH_TOKEN;delete process.env.BLOB_READ_WRITE_TOKEN;
await mkdir('.test-runtime',{recursive:true});
const compiled=await build({stdin:{contents:`
 export {POST as rewardPost} from './app/api/rewards/quote/route';export {previewRewards} from './modules/order/rewards-server';export * from './modules/order/rewards';
 export * from './lib/database';export * from './modules/order/first-purchase';export * from './modules/order/first-purchase-server';
 export * from './modules/catalog/product-schedule';export {registerCustomer,currentCustomer} from './modules/catalog/customers';
 export {readProduct,readProducts} from './modules/catalog/server';export {saveProduct} from './modules/catalog/catalog-service';
 export {createCheckout,quoteCheckout} from './modules/catalog/checkout';export {cartAvailability,cartSummary} from './modules/catalog/cart-availability';
 export {encrypt,hash,myOrder} from './modules/order/order-server';export {invoiceText} from './modules/order/order-types';
 export {confirmPayment} from './modules/order/fulfilment';export {POST as orderPost,DELETE as orderDelete} from './app/api/order/route';
 export {GET as catalogQuoteGet} from './app/api/order/catalog/route';export {POST as resumePost} from './app/api/order/first-purchase/route';
 export {GET as customerGet} from './app/api/customer/route';export {POST as proofPost} from './app/api/order/proof/route';
`,resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,external:['@libsql/client','@vercel/blob','@hyzyla/pdfium'],banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},plugins:[{name:'next',setup(b){b.onResolve({filter:/^next\/(headers|navigation)$/},a=>({path:a.path+'.js',external:true}))}}]});
await writeFile('.test-runtime/rewards.mjs',compiled.outputFiles[0].contents);
const m=await import(pathToFileURL(path.resolve('.test-runtime/rewards.mjs'))),client=m.getSqlClient();
await migrate(client,new URL('../migrations/',import.meta.url));
const originalFetch=globalThis.fetch;
let messages=[];
globalThis.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url);assert.equal(url.hostname,'api.telegram.org');if(typeof init.body==='string')messages.push(JSON.parse(init.body));return Response.json({ok:true,result:{message_id:50}});};
const request=(route,body,cookie='')=>new Request('https://elite.test'+route,{method:body===undefined?'GET':'POST',headers:{Origin:'https://elite.test','Content-Type':'application/json',Cookie:cookie},...(body===undefined?{}:{body:JSON.stringify(body)})});
const payload={name:'Simulated Buyer',phone:'081234567890',address:'Jalan Pengujian Nomor 12 RT 01',postcode:'78243',item:'Simulated vintage',quantity:1,itemAmount:185000,quoteId:'f'.repeat(64),consent:true};
let buyer,buyerCookie,product,selection;
beforeEach(async()=>{
 for(const table of ['purchase_voucher_claims','purchase_vouchers','first_purchase_discounts','shipments','orders','catalog_sales','catalog_checkouts','stock_history','size_groups','products','customer_sessions','customers','photos','limits','request_limits','shipping_quotes','settings'])await client.execute('DELETE FROM '+table);
 messages=[];
 await client.execute({sql:'INSERT INTO settings(id,bot_cipher,chat_id,webhook_cipher,webhook_active) VALUES(1,?,?,?,1)',args:[await m.encrypt('SIMULATED_BOT'),'123456',await m.encrypt('SIMULATED_HOOK')]});
 const q={id:'f'.repeat(64),amount:38000,grams:1000,service:'EZ',destination:{id:90,label:'Simulated destination',postalCode:'78243'},checkedAt:Date.now(),expiresAt:Date.now()+3600000};
 await client.execute({sql:'INSERT INTO shipping_quotes VALUES(?,?,?)',args:[q.id,JSON.stringify(q),q.expiresAt]});
 const registered=await m.registerCustomer({name:'Simulated Buyer',identity:'buyer@example.test',password:'SIMULATED_PASSWORD_123',consent:true},null);
 buyerCookie='elite_customer='+registered.token;buyer=await m.currentCustomer(buyerCookie);
 const now=new Date().toISOString(),photo='10000000-0000-4000-8000-000000000000';
 await client.execute({sql:'INSERT INTO photos VALUES(?,?,?,?,?)',args:[photo,'image/png',80,'manual',now]});
 await client.execute({sql:"INSERT INTO products(id,shortcode,instagram_url,name,brand,category,color,price,condition,defects,photo_key,created_at,updated_at,published_at,status,reviewed) VALUES('product','product','','Simulated Polo','Beanpole','Polo','Black',185000,'Very good','Tidak ada',?,?,?,?,'published',1)",args:[photo,now,now,now]});
 await client.execute("INSERT INTO size_groups(id,product_id,fits,qty,length_cm,width_cm) VALUES('group','product','[\"M\"]',10,60,50)");
 product=await m.readProduct('product');selection={lines:[{productId:'product',groupId:'group',quantity:1}]};
});
after(async()=>{globalThis.fetch=originalFetch;client.close();assert.equal(path.dirname(dir),os.tmpdir());assert.ok(path.basename(dir).startsWith('elite-rewards-'));await rm(dir,{recursive:true,force:true,maxRetries:8,retryDelay:200});});
async function create(cookie=buyerCookie,extra={}){return m.orderPost(request('/api/order',{...payload,...extra},cookie));}
async function discounted(){const response=await create();assert.equal(response.status,201,JSON.stringify(await response.clone().json()));return {order:await response.json(),cookie:buyerCookie+'; '+response.headers.get('set-cookie').split(';')[0]};}
async function voucher(changes={}){
 const v={id:'reward-10',label:'ELITE Reward personal',owner_user_id:buyer.id,type:'percentage',percentage:10,fixed_amount:null,minimum_order:0,maximum_discount:null,valid_from:Date.now()-1000,valid_until:Date.now()+86400000,usage_limit:1,usage_count:0,applicable_categories:'[]',applicable_products:'[]',first_order_only:0,active:1,...changes};
 await client.execute({sql:`INSERT INTO purchase_vouchers(${Object.keys(v).join(',')}) VALUES(${Object.keys(v).map(()=>'?').join(',')})`,args:Object.values(v)});return v;
}
async function preview(input={context:'cart',lines:selection.lines},cookie=buyerCookie){const r=await m.rewardPost(request('/api/rewards/quote',input,cookie));return {status:r.status,...await r.json()};}
test('guest sees normal price and cannot use a personal voucher',async()=>{await voucher();const q=await preview(undefined,'');assert.equal(q.discount,0);assert.equal(q.net,185000);assert.equal(q.loggedIn,false);assert.equal(q.options.length,0);assert.equal((await create('',{rewardChoice:'reward-10'})).status,409);});
test('logged-in customer without eligible rewards receives no false discount',async()=>{const r=await create(buyerCookie,{rewardChoice:'none'}),o=await r.json();await client.execute({sql:"UPDATE orders SET confirmed_at=?,payment_state='payment_confirmed' WHERE id=?",args:[Date.now(),o.id]});const q=await preview();assert.equal(q.discount,0);assert.equal(q.options.length,0);});
test('existing first-purchase reward is server-priced consistently in product, cart and checkout',async()=>{const p=await preview({context:'product',productId:'product'}),c=await preview();assert.equal(p.personalPrice,175750);assert.equal(c.discount,9250);const checkout=await m.createCheckout(selection),token=new URL(checkout.url,'https://elite.test').searchParams.get('catalog'),q=await preview({context:'checkout',catalogToken:token});assert.equal(q.discount,9250);const reply=await create(buyerCookie,{catalogToken:token,itemAmount:1,rewardChoice:'auto'}),o=await reply.json();assert.equal(reply.status,201);assert.equal(o.item_subtotal,185000);assert.equal(o.discount_amount,9250);assert.equal(o.discount_voucher_id,'first-purchase-5');assert.equal(o.total,213750);});
test('percentage reward selects best value and can be chosen explicitly',async()=>{await voucher();const q=await preview();assert.equal(q.options.length,2);assert.equal(q.selected.id,'reward-10');assert.equal(q.discount,18500);const p=await preview({context:'product',productId:'product'});assert.equal(p.personalPrice,166500);const c=await preview({context:'cart',lines:selection.lines,choice:'first-purchase-5'});assert.equal(c.discount,9250);const o=await (await create(buyerCookie,{rewardChoice:'reward-10'})).json();assert.equal(o.discount_amount,18500);assert.equal(o.discount_label,'ELITE Reward personal');assert.equal(o.total,204500);assert.equal((await client.execute('SELECT * FROM first_purchase_discounts')).rows.length,0);});
test('fixed amount uses whole rupiah, cannot exceed eligible subtotal and does not claim per-product exact price',async()=>{await voucher({type:'fixed',percentage:null,fixed_amount:50000});const q=await preview();assert.equal(q.discount,50000);assert.equal(q.net,135000);assert.equal((await preview({context:'product',productId:'product'})).personalPrice,null);await client.execute('UPDATE purchase_vouchers SET fixed_amount=999999');assert.equal((await preview()).discount,185000);await client.execute('UPDATE purchase_vouchers SET fixed_amount=50000');const o=await (await create(buyerCookie,{rewardChoice:'reward-10'})).json();assert.equal(o.total,173000);});
test('minimum purchase shows remaining amount without presenting a false exact product price',async()=>{await voucher({minimum_order:285000});const q=await preview();const option=q.options.find(o=>o.id==='reward-10');assert.equal(option.discount,0);assert.match(option.requirement,/100\.000/);assert.equal((await preview({context:'cart',lines:selection.lines,choice:'reward-10'})).status,409);await client.execute('UPDATE purchase_vouchers SET minimum_order=100000');assert.equal((await preview({context:'product',productId:'product'})).personalPrice,null);assert.equal((await preview()).discount,18500);});
test('maximum discount cap applies in cart and final order without claiming exact product price',async()=>{await voucher({percentage:30,maximum_discount:12000});assert.equal((await preview()).discount,12000);assert.equal((await preview({context:'product',productId:'product'})).personalPrice,null);const o=await (await create(buyerCookie,{rewardChoice:'reward-10'})).json();assert.equal(o.discount_amount,12000);assert.equal(o.total,211000);});
test('expired, future, inactive and exhausted vouchers cannot be submitted',async()=>{for(const changes of [{valid_until:Date.now()-1,valid_from:0},{valid_from:Date.now()+100000},{active:0},{usage_count:1}]){await client.execute('DELETE FROM purchase_vouchers');await voucher(changes);assert.equal((await preview()).options.some(o=>o.id==='reward-10'),false);assert.equal((await create(buyerCookie,{rewardChoice:'reward-10'})).status,409);}});
test('another customer cannot see or redeem a personal voucher',async()=>{const other=await m.registerCustomer({name:'Other Buyer',identity:'other@example.test',password:'SIMULATED_PASSWORD_123',consent:true},null),otherCustomer=await m.currentCustomer('elite_customer='+other.token);await voucher({owner_user_id:otherCustomer.id});assert.equal((await preview()).options.some(o=>o.id==='reward-10'),false);assert.equal((await create(buyerCookie,{rewardChoice:'reward-10'})).status,409);});
test('category and product rules discount only eligible items, not manual order claims',async()=>{await voucher({applicable_categories:'["Polo"]',applicable_products:'["product"]'});assert.equal((await preview()).discount,18500);assert.equal((await preview({context:'manual',itemAmount:185000})).options.find(o=>o.id==='reward-10').discount,0);assert.equal((await create(buyerCookie,{rewardChoice:'reward-10'})).status,409);await client.execute("UPDATE purchase_vouchers SET applicable_categories='[\"Jacket\"]'");assert.equal((await preview()).options.find(o=>o.id==='reward-10').discount,0);});
test('no stacking and explicit no-voucher choice are respected by final pricing',async()=>{await voucher();assert.equal((await preview()).discount,18500);const q=await preview({context:'cart',lines:selection.lines,choice:'none'});assert.equal(q.discount,0);const o=await (await create(buyerCookie,{rewardChoice:'none'})).json();assert.equal(o.total,223000);assert.equal(o.discount_amount,0);});
test('limited voucher reserves only one parallel invoice; confirmation redeems once',async()=>{await voucher();const replies=await Promise.all([create(buyerCookie,{rewardChoice:'reward-10'}),create(buyerCookie,{rewardChoice:'reward-10'})]);assert.deepEqual(replies.map(r=>r.status).sort(),[201,409]);const reply=replies.find(r=>r.status===201),o=await reply.json();assert.equal((await client.execute('SELECT usage_count FROM purchase_vouchers')).rows[0].usage_count,0);await client.execute({sql:"UPDATE orders SET proof_key='simulated',status='submitted',delivery_chat='123456',invoice_message='50' WHERE id=?",args:[o.id]});await m.confirmPayment(o.id,'123456',50);await m.confirmPayment(o.id,'123456',50);assert.equal((await client.execute('SELECT usage_count FROM purchase_vouchers')).rows[0].usage_count,1);assert.ok((await client.execute('SELECT redeemed_at FROM purchase_voucher_claims')).rows[0].redeemed_at);});
test('editing a reserved invoice recalculates and cancellation releases its unredeemed claim',async()=>{await voucher();const reply=await create(buyerCookie,{rewardChoice:'reward-10'}),o=await reply.json(),cookie=buyerCookie+'; '+reply.headers.get('set-cookie').split(';')[0];const updated=await create(cookie,{itemAmount:200000,rewardChoice:'reward-10'});assert.equal(updated.status,200);assert.equal((await updated.json()).discount_amount,20000);const q=await preview({context:'manual',itemAmount:200000,choice:'reward-10'},cookie);assert.equal(q.discount,20000);const req=new Request('https://elite.test/api/order',{method:'DELETE',headers:{Origin:'https://elite.test',Cookie:cookie}});assert.equal((await m.orderDelete(req)).status,200);assert.equal((await client.execute('SELECT * FROM purchase_voucher_claims')).rows.length,0);assert.equal((await preview()).selected.id,'reward-10');});
test('replacing a reserved reward releases only that invoice and reserves its replacement',async()=>{await voucher();const reply=await create(buyerCookie,{rewardChoice:'reward-10'}),cookie=buyerCookie+'; '+reply.headers.get('set-cookie').split(';')[0];assert.equal((await create(cookie,{rewardChoice:'first-purchase-5'})).status,200);assert.equal((await client.execute('SELECT * FROM purchase_voucher_claims')).rows.length,0);assert.equal((await client.execute('SELECT * FROM first_purchase_discounts')).rows.length,1);});
test('expired unpaid reservations are released, but uploaded proof remains reserved',async()=>{await voucher();const r=await create(buyerCookie,{rewardChoice:'reward-10'}),o=await r.json();await client.execute({sql:'UPDATE orders SET created_at=? WHERE id=?',args:[Date.now()-8*86400000,o.id]});assert.equal((await preview()).selected.id,'reward-10');const next=await create(buyerCookie,{rewardChoice:'reward-10'}),n=await next.json();await client.execute({sql:"UPDATE orders SET created_at=?,proof_key='proof',status='submitted' WHERE id=?",args:[Date.now()-8*86400000,n.id]});assert.equal((await preview()).options.some(o=>o.id==='reward-10'),false);});
test('first-order-only rewards cannot be reserved twice across different reward types',async()=>{await voucher({first_order_only:1});const first=await create(buyerCookie,{rewardChoice:'reward-10'});assert.equal(first.status,201);const q=await preview();assert.equal(q.options.length,0);assert.equal((await create(buyerCookie,{rewardChoice:'first-purchase-5'})).status,409);});
test('SOLD and scheduled products never receive actionable discounted prices or checkout access',async()=>{await voucher();await client.execute("UPDATE size_groups SET qty=0");assert.equal((await preview({context:'product',productId:'product'})).personalPrice,null);assert.equal((await preview()).status,409);await assert.rejects(m.createCheckout(selection));await client.execute('UPDATE size_groups SET qty=1');await client.execute({sql:'UPDATE products SET orderable_at=?',args:[new Date(Date.now()+60000).toISOString()]});assert.equal((await preview({context:'product',productId:'product'})).personalPrice,null);assert.equal((await preview()).status,409);});
test('tampered prices, discount values, arbitrary fields and foreign-origin quotes are rejected or ignored safely',async()=>{await voucher();for(const extra of [{discountAmount:100000},{discount_amount:100000},{discount_label:'FREE'},{discount_voucher_id:'reward-10'}])assert.equal((await create(buyerCookie,extra)).status,400);const q=await preview({context:'cart',lines:[{...selection.lines[0],unitPrice:1}],choice:'reward-10'});assert.equal(q.subtotal,185000);const req=request('/api/rewards/quote',{context:'cart',lines:selection.lines},buyerCookie);req.headers.set('origin','https://other.test');assert.equal((await m.rewardPost(req)).status,403);assert.equal((await preview({context:'cart',lines:selection.lines,discount:10000})).status,400);});
test('mixed product restrictions never discount an ineligible product',()=>{const rule={id:'r',label:'R',type:'percentage',percentage:10,fixedAmount:null,minimumOrder:0,maximumDiscount:null,products:['eligible'],categories:['Polo']};const q=m.evaluateReward(rule,[{productId:'eligible',category:'Polo',amount:100000},{productId:'other',category:'Polo',amount:900000}]);assert.equal(q.discount,10000);});
test('invalid and expired checkout links retain their actionable validation errors in reward preview',async()=>{assert.equal((await preview({context:'checkout',catalogToken:'bad'})).status,400);const checkout=await m.createCheckout(selection),token=new URL(checkout.url,'https://elite.test').searchParams.get('catalog');await client.execute('UPDATE catalog_checkouts SET expires_at=0');const q=await preview({context:'checkout',catalogToken:token});assert.equal(q.status,410);assert.match(q.error,/berakhir/);});
