'use client';
import {useSaleClock} from '@/components/use-sale-clock';
import {catalogInventory,catalogListing} from '@/modules/catalog/sold-lifecycle';
import {orderingLocked} from '@/modules/catalog/product-schedule';
import {CatalogFilters} from '@/components/catalog-filters';
import {CATEGORIES,DEFAULT_FEATURES,FEATURE_GROUPS,selectedValues,type Taxonomy} from '@/modules/catalog/taxonomy';
import {CustomerSupport} from '@/components/customer-support';
import {CustomerAccount} from '@/components/customer-account';
import {ProductCard} from '@/components/product-card';
import {catalogPage, catalogPageNumbers, parseCatalogPage} from '@/modules/catalog/catalog-pagination';
import { ProductDetail } from '@/components/product-detail';
import { reconcileReturnedCart } from '@/modules/catalog/cart-return';
import { checkoutDestination } from '@/modules/catalog/checkout-navigation';
import { catalogRequest } from '@/modules/catalog/catalog-request';
import {cartAvailability,cartSummary} from '@/modules/catalog/cart-availability';
import {CartItemStatus} from '@/components/cart-item-status';
import { BrandLogo } from '@/components/brand-logo';
import { useState,useEffect,useRef,useMemo } from 'react';
import { Search,Camera as Instagram,RefreshCw,X,ShoppingBag,Plus,Minus,ChevronLeft,ChevronRight } from 'lucide-react';
import { Select,SelectTrigger,SelectContent,SelectItem,SelectValue } from '@/components/ui/select';
import { Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Skeleton } from '@/components/ui/skeleton';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { FITS, fitLabel,choiceLabel, type Product,availableGroups,displayPrice,money,matchesProduct,matchesSizePrice,isSold } from '@/modules/catalog/catalog-types';
const defaults={q:'',size:'all',brand:'all',category:'all',features:'all',min:'',max:'',sort:'newest',availability:'all'};
function Picker({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="filter-control" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function Catalog({productId,initialProduct,archive=false}:{productId?:string;initialProduct?:Product;archive?:boolean}={}){
 const [filters,setFilters]=useState(defaults),[ready,setReady]=useState(false),[products,setProducts]=useState<Product[]>(initialProduct?[initialProduct]:[]),[catalogLoaded,setCatalogLoaded]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[refreshing,setRefreshing]=useState(false);
 const [page,setPage]=useState(1);
 const saleNow=useSaleClock(updated,Math.max(0,...products.map(p=>p.orderableAt?Date.parse(p.orderableAt):0)));
 const grid=useRef<HTMLDivElement>(null);
 const [taxonomy,setTaxonomy]=useState<Taxonomy>({categories:CATEGORIES,features:DEFAULT_FEATURES,groups:FEATURE_GROUPS});
 const [cart,setCart]=useState<{productId:string;groupId:string;quantity:number;name:string;label:string}[]>([]),[checkoutBusy,setCheckoutBusy]=useState(false),[checkoutError,setCheckoutError]=useState('');
 const [cartOpen,setCartOpen]=useState(false),[addedNote,setAddedNote]=useState('');
 const [detail,setDetail]=useState<Product|null>(initialProduct??null),[detailError,setDetailError]=useState(''),[backHref,setBackHref]=useState('/');
 const restore=useRef<number|null>(null),pending=useRef(false),filtersRef=useRef(filters);filtersRef.current=filters;
 async function load(){
  if(pending.current)return;pending.current=true;
  const read=(path:string)=>catalogRequest(path,{cache:'no-store'});
  try{
   const [catalogResult,detailResult]=await Promise.allSettled([read('/api/catalog'),productId?read('/api/products/'+encodeURIComponent(productId)):Promise.resolve(null)]);
   const errors:string[]=[];
   if(catalogResult.status==='fulfilled'){
    const data=catalogResult.value;setProducts([...data.products,...(data.recentlySold??[])]);setCatalogLoaded(true);if(data.taxonomy)setTaxonomy(data.taxonomy);setUpdated(data.asOf);
   }else errors.push(catalogResult.reason.message);
   if(productId){
    if(detailResult.status==='fulfilled'){const p=detailResult.value.product as Product;setDetail(p);setDetailError('');setProducts(all=>[...all.filter(item=>item.id!==p.id),p]);}
    else if(detailResult.reason.status===404){setDetail(null);setDetailError(detailResult.reason.message);}
    else errors.push(detailResult.reason.message);
   }
   setError(errors.join(' '));
  }finally{setLoading(false);setRefreshing(false);pending.current=false}
 }
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const next={...defaults};Object.keys(next).forEach(k=>{const v=params.get(k);if(v!=null)(next as any)[k]=v});if(!['newest','low','high'].includes(next.sort))next.sort='newest';setFilters(next);setPage(parseCatalogPage(params.get('page')));setReady(true);try{const s=JSON.parse(sessionStorage.getItem('elite.catalog.navigation')??'null');if(productId&&typeof s?.url==='string'&&(s.url==='/'||s.url.startsWith('/?')||s.url==='/recently-sold'||s.url.startsWith('/recently-sold?')))setBackHref(s.url);if(s?.url===window.location.pathname+window.location.search&&typeof s.y==='number')restore.current=s.y}catch{}try{const saved=JSON.parse(sessionStorage.getItem('elite.catalog.cart')||'[]');if(Array.isArray(saved)){const valid=saved.filter(x=>typeof x?.productId==='string'&&typeof x?.groupId==='string'&&Number.isSafeInteger(x?.quantity)&&x.quantity>0).slice(0,20);const returned=reconcileReturnedCart(valid,JSON.parse(sessionStorage.getItem('elite.catalog.checkout')??'null'),window.location.hash);setCart(returned.cart);if(returned.completed){sessionStorage.removeItem('elite.catalog.checkout');window.history.replaceState(null,'',window.location.pathname+window.location.search);setAddedNote('Pesanan sudah dikirim. Silakan pilih barang lainnya.')}}}catch{}void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);const focus=()=>{void load()};window.addEventListener('focus',focus);window.addEventListener('pageshow',focus);document.addEventListener('visibilitychange',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);window.removeEventListener('pageshow',focus);document.removeEventListener('visibilitychange',focus)}},[]);
 useEffect(()=>{if(!loading&&restore.current!=null){const y=restore.current;restore.current=null;requestAnimationFrame(()=>window.scrollTo({top:y,behavior:'instant'}))}},[loading,products]);
 useEffect(()=>{if(ready)try{sessionStorage.setItem('elite.catalog.cart',JSON.stringify(cart))}catch{}},[cart,ready]);
 useEffect(()=>{if(!cart.length)setCartOpen(false)},[cart.length]);
 function pick(p:Product,g:Product['groups'][number]){if(isSold(p)||orderingLocked(p,saleNow)||cart.reduce((n,x)=>n+x.quantity,0)>=20||(cart.find(x=>x.groupId===g.id)?.quantity??0)>=(g.qty??0))return;setCheckoutError('');setAddedNote(p.name+' · '+fitLabel(g)+' ditambahkan ke keranjang.');setCart(all=>{const old=all.find(x=>x.groupId===g.id);if(all.reduce((n,x)=>n+x.quantity,0)>=20||(old?.quantity||0)>=(g.qty||0))return all;return old?all.map(x=>x.groupId===g.id?{...x,quantity:x.quantity+1}:x):[...all,{productId:p.id,groupId:g.id,quantity:1,name:p.name,label:choiceLabel(g)}]})}
 function cartQuantity(groupId:string,delta:number){setCart(all=>all.map(x=>x.groupId===groupId?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0));setCheckoutError('')}
 const cartRows=cartAvailability(cart,products,catalogLoaded,saleNow),cartCount=cart.reduce((n,x)=>n+x.quantity,0),cartState=cartSummary(cartRows);
 async function checkout(){setCheckoutBusy(true);setCheckoutError('');try{const v=await catalogRequest('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lines:cart.map(({productId,groupId,quantity})=>({productId,groupId,quantity}))})});const basket=crypto.randomUUID(),target=checkoutDestination(v.url,window.location.origin,basket);try{sessionStorage.setItem('elite.catalog.checkout',JSON.stringify({id:basket,lines:cart.map(({productId,groupId,quantity})=>({productId,groupId,quantity}))}))}catch{}remember();window.location.assign(target.href)}catch(e){setCheckoutError((e as Error).message);void load()}finally{setCheckoutBusy(false)}}
 function change(key:keyof typeof defaults,value:string){restore.current=null;setPage(1);setFilters(f=>({...f,[key]:value}))}
 function resetFilters(next=defaults){restore.current=null;setPage(1);setFilters(next)}
 function remember(){if(productId)return;try{sessionStorage.setItem('elite.catalog.navigation',JSON.stringify({url:window.location.pathname+window.location.search,y:window.scrollY}))}catch{}}
 const availableFits=useMemo(()=>{const base=['S','M','L','XL','XXL'];return [...base,...FITS.filter(size=>!base.includes(size)&&products.some(product=>product.groups.some(group=>group.fits.includes(size))))]},[products]);
 const brands=[...new Set(products.map(p=>p.brand))].filter(Boolean).sort();
 const inventory=useMemo(()=>catalogInventory(products,saleNow||Date.parse(updated)||Date.now()),[products,saleNow,updated]);
 const shown=useMemo(()=>catalogListing(products,filters,taxonomy.features,saleNow||Date.parse(updated)||Date.now(),archive),[products,filters,taxonomy,saleNow,updated,archive]);
 const {page:currentPage,pageCount,start,items:pageItems}=catalogPage(shown,page);
 const pageNumbers=catalogPageNumbers(currentPage,pageCount);
 useEffect(()=>{if(ready&&!loading&&page!==currentPage)setPage(currentPage)},[ready,loading,page,currentPage]);
 useEffect(()=>{if(!ready||loading||productId)return;const q=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v&&(defaults as any)[k]!==v)q.set(k,v)});if(currentPage>1)q.set('page',String(currentPage));window.history.replaceState(null,'',window.location.pathname+(q.size?'?'+q:''));},[filters,ready,loading,productId,currentPage]);
 function changePage(next:number){restore.current=null;setPage(next);requestAnimationFrame(()=>grid.current?.scrollIntoView({block:'start',behavior:'instant'}))}
 const chosenSizes=selectedValues(filters.size),chosenBrands=selectedValues(filters.brand),chosenCategories=selectedValues(filters.category),chosenFeatures=selectedValues(filters.features);
 const active=chosenSizes.length+chosenBrands.length+chosenCategories.length+chosenFeatures.length+Number(!!filters.min)+Number(!!filters.max);
 const filterLabels=[...chosenSizes.map(s=>'Fit '+s),...chosenBrands,...chosenCategories,...chosenFeatures.map(id=>taxonomy.features.find(f=>f.id===id)?.label??id)];

 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_available_stock',title:'Filter katalog stok',description:'Tampilkan barang terbit yang masih tersedia menurut nama, fit, brand, kategori, dan harga. Tidak mengubah stok.',inputSchema:{type:'object',properties:{q:{type:'string'},size:{type:'string'},brand:{type:'string'},category:{type:'string'},features:{type:'string'},min:{type:'number',minimum:0},max:{type:'number',minimum:0},sort:{type:'string',enum:['newest','low','high']}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Filter tidak valid.');for(const key of Object.keys(input))if(!Object.hasOwn(defaults,key))throw new Error('Filter tidak dikenal.');for(const key of ['min','max'])if(input[key]!=null&&(typeof input[key]!=='number'||!Number.isFinite(input[key])||input[key]<0))throw new Error('Harga tidak valid.');for(const key of ['q','size','brand','category','features','sort'])if(input[key]!=null&&typeof input[key]!=='string')throw new Error('Filter harus teks.');if(input.size&&selectedValues(input.size).some(s=>!FITS.includes(s)))throw new Error('Fit tidak tersedia.');if(input.sort&&!['newest','low','high'].includes(input.sort))throw new Error('Pengurutan tidak valid.');const next={...filtersRef.current,...input,min:input.min==null?filtersRef.current.min:String(input.min),max:input.max==null?filtersRef.current.max:String(input.max)};restore.current=null;setPage(1);setFilters(next);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {count:catalogListing(products,next,taxonomy.features,Date.parse(updated)||Date.now(),archive).length,filters:next};}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[products,taxonomy]);
 return <main className="catalog-shell">
  <header className="masthead"><a className="wordmark" href="/"><BrandLogo/><small>CURATED VINTAGE</small></a><div className="header-links"><CustomerAccount/><a className="quiet-link instagram-header" href="https://www.instagram.com/elite.vtg/" target="_blank" rel="noopener noreferrer">Instagram <Instagram size={16}/></a></div></header>
  {!productId&&<>
   <section className="catalog-title"><h1>{archive?'Recently Sold':'Koleksi tersedia'}</h1><p className="muted">{archive?'Pilihan yang sudah menemukan pemilik baru.':'Pilihan terkurasi. Temukan yang cocok untuk Anda.'}</p>{archive&&<a className="text-button archive-back" href="/?availability=available">Lihat koleksi tersedia</a>}</section>
   <div className="searchbox"><Search size={19}/><input aria-label="Cari barang, brand, atau model" value={filters.q} onChange={event=>change('q',event.target.value)} placeholder="Cari barang, brand, atau model..."/>{filters.q&&<button aria-label="Hapus pencarian" className="icon-button" onClick={()=>change('q','')}><X size={18}/></button>}</div>
   <div className="filterbar">
    <CatalogFilters filters={filters} onChange={change} onReset={()=>resetFilters({...defaults,q:filters.q,sort:filters.sort})} sizes={availableFits} brands={brands} categories={taxonomy.categories} count={shown.length} active={active} loading={loading}/>
    {!archive&&<div className="sort-wrap"><Picker label="Urutkan barang" value={filters.sort} onChange={value=>change('sort',value)} options={[{value:'newest',label:'Terbaru'},{value:'low',label:'Harga terendah'},{value:'high',label:'Harga tertinggi'}]}/></div>}
    <span className="results" aria-live="polite">{loading?'Memuat stok…':archive?`${shown.length} barang terjual`:`${shown.filter(p=>!isSold(p)).length} barang tersedia${shown.some(isSold)?' · '+shown.filter(isSold).length+' SOLD':''}`}</span>
   </div>
   {(active>0||filters.q)&&<div className="active-filters"><span>{filterLabels.join(' · ')}{filters.min||filters.max?` · ${money(filters.min?Number(filters.min):0)} – ${filters.max?money(Number(filters.max)):'tanpa batas'}`:''}</span><button onClick={()=>resetFilters()} className="text-button">Reset semua</button></div>}
  </>}

 {error&&<div role="alert" className="notice error"><p>{error}</p><button className="button secondary" onClick={()=>{setRefreshing(true);void load()}} disabled={refreshing}><RefreshCw size={16}/>Coba lagi</button></div>}
 {productId?(loading&&!detail?<div className="detail-loading"><Skeleton className="skeleton-photo"/><p className="muted">Memuat produk…</p></div>:detail?<ProductDetail now={saleNow} product={detail} backHref={backHref} cart={cart} onPick={pick} cartCount={cartCount} features={taxonomy.features} onOpenCart={()=>setCartOpen(true)}/>:<section className="empty-state"><h1>Produk belum tersedia</h1><p>{detailError||error||'Barang ini belum diterbitkan.'}</p><a className="button secondary" href={backHref}>Kembali ke koleksi</a></section>):<> {loading?<div className="product-grid">{[1,2,3,4].map(i=><div key={i}><Skeleton className="skeleton-photo"/><Skeleton className="skeleton-line"/></div>)}</div>:shown.length?<section className="catalog-products" aria-label={archive?'Recently Sold':'Koleksi barang'}><div className="product-grid" ref={grid}>{pageItems.map(p=><ProductCard now={saleNow} key={p.id} product={p} onNavigate={remember}/>)}</div><div className="catalog-pagination"><p className="pagination-summary" aria-live="polite">{start+1}–{start+pageItems.length} dari {shown.length} barang<span>Halaman {currentPage} dari {pageCount}</span></p>{pageCount>1&&<nav className="pagination-controls" aria-label="Halaman katalog"><button className="pagination-arrow" aria-label="Halaman sebelumnya" disabled={currentPage===1} onClick={()=>changePage(currentPage-1)}><ChevronLeft size={18}/><span>Sebelumnya</span></button>{pageNumbers.map((number,index)=><span className="pagination-number-wrap" key={number}>{index>0&&number-pageNumbers[index-1]>1&&<span className="pagination-gap" aria-hidden="true">…</span>}<button className="pagination-number" aria-label={'Halaman '+number} aria-current={number===currentPage?'page':undefined} onClick={()=>changePage(number)}>{number}</button></span>)}<button className="pagination-arrow" aria-label="Halaman berikutnya" disabled={currentPage===pageCount} onClick={()=>changePage(currentPage+1)}><span>Berikutnya</span><ChevronRight size={18}/></button></nav>}</div></section>:!error?<Empty className="empty-state"><EmptyHeader><div className="empty-mark">E.</div><EmptyTitle>{archive?'Belum ada barang di Recently Sold':products.length?'Belum ada barang yang cocok':'Barang tersedia akan tampil di sini'}</EmptyTitle><EmptyDescription>{archive?'Lihat koleksi tersedia untuk menemukan pilihan lainnya.':products.length?'Coba fit lain atau ubah filter Anda.':'Koleksi sedang disiapkan. Silakan cek kembali.'}</EmptyDescription></EmptyHeader>{products.length?<button className="button secondary" onClick={()=>resetFilters()}>Reset pencarian dan filter</button>:null}</Empty>:null}</>}

 {!productId&&!archive&&inventory.recentlySold.length>0&&<aside className="recently-sold-link"><div><h2>Recently Sold</h2><p>Beberapa pilihan yang sudah terjual.</p></div><a className="text-button" href="/recently-sold" onClick={remember}>Lihat arsip <ChevronRight size={16}/></a></aside>}
 <p className="sr-only" role="status" aria-live="polite">{addedNote}</p>
 {cart.length>0&&<Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetTrigger asChild><button className="cart-shortcut" onClick={()=>setCartOpen(true)} aria-label={`Buka keranjang, ${cartCount} unit`}><ShoppingBag size={18}/> Keranjang · {cartCount} unit <strong>{cartState.label}</strong></button></SheetTrigger><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Keranjang Anda</SheetTitle><SheetDescription>Periksa ukuran dan jumlah sebelum melanjutkan.</SheetDescription></SheetHeader><section className="catalog-cart" aria-label="Barang pilihan"><div className="cart-heading"><h2><ShoppingBag size={20}/>{cartCount} unit dipilih</h2><button className="text-button" onClick={()=>{setCart([]);setCartOpen(false);setAddedNote('Keranjang dikosongkan.')}}>Kosongkan</button></div>{cartRows.map(x=><div className="cart-row" key={x.groupId}><div className="cart-item-info">{x.photoKey&&<img className="cart-item-photo" src={'/api/photos/'+x.photoKey} alt="" width={48} height={60}/>}<div><a href={'/produk/'+x.productId} onClick={remember}><strong>{x.name}</strong></a><CartItemStatus row={x}/><button className="text-button cart-remove" aria-label={`Hapus ${x.name} ${x.label} dari keranjang`} onClick={()=>{setCart(all=>all.filter(item=>item.groupId!==x.groupId));setCheckoutError('');setAddedNote(x.name+' dihapus dari keranjang.')}}>Hapus</button></div></div><div className="stepper"><button aria-label={`Kurangi jumlah ${x.name} ${x.label}`} onClick={()=>cartQuantity(x.groupId,-1)}><Minus size={16}/></button><span>{x.quantity}</span><button aria-label={`Tambah jumlah ${x.name} ${x.label}`} disabled={x.scheduled||x.pending||cartCount>=20||x.quantity>=x.stock} onClick={()=>cartQuantity(x.groupId,1)}><Plus size={16}/></button></div></div>)}{checkoutError&&<p className="field-error" role="alert">{checkoutError}</p>}<div className="cart-footer"><strong>{cartState.label}</strong><button className="button primary" onClick={()=>void checkout()} disabled={checkoutBusy||!cartState.canCheckout}>{checkoutBusy?'Membuka pembayaran…':cartRows.some(x=>x.pending)?'Memeriksa stok…':'Lanjut ke pembayaran'}</button></div><p className="help-text">Ongkir dihitung di pembayaran. Stok belum ditahan sampai pesanan dikonfirmasi ELITE.</p><button className="button secondary continue-shopping" onClick={()=>setCartOpen(false)}>Lanjut belanja</button></section></SheetContent></Sheet>}
 <CustomerSupport hasCart={cart.length>0}/><div className="catalog-status"><span>{updated?`Stok diperbarui ${new Date(updated).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'})} WIB`:' '}</span><button className="text-button" onClick={()=>{setRefreshing(true);void load()}} disabled={refreshing}><RefreshCw size={14} className={refreshing?'spin':''}/> Perbarui stok</button></div><footer className="footer"><span className="footer-brand">© {new Date().getFullYear()} <BrandLogo/></span><span>Curated pieces. Actual measurements.</span>{!archive&&<a className="footer-sold-link" href="/recently-sold" onClick={remember}>Recently Sold</a>}</footer></main>
}
