"use client";
import Link from "next/link";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { Package,RefreshCw,Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { dateLabel } from "@/modules/order/order-types";
import { trackingStageLabels,type CustomerTracking } from "@/modules/order/tracking-types";

export function TrackingCard({lookup=false}:{lookup?:boolean}){
 const [data,setData]=useState<CustomerTracking|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(""),[info,setInfo]=useState(""),[invoice,setInvoice]=useState(""),[phone,setPhone]=useState("");
 const token=useRef(""),alive=useRef(true),current=useRef<CustomerTracking|null>(null);current.current=data;
 async function load(silent=false){if(!silent)setBusy(true);try{const r=await fetch("/api/order/tracking",{headers:token.current?{Authorization:"Bearer "+token.current}:{},signal:AbortSignal.timeout(45000)}),v=await r.json() as CustomerTracking&{error?:string};if(!r.ok||v.error){if(r.status===404&&!current.current){if(alive.current)setData(null);return;}throw new Error(v.error||"Status pesanan belum dapat dimuat.");}if(alive.current){setData(v);setError("");}}catch(e){if(alive.current&&!silent)setError(e instanceof Error?e.message:"Status belum dapat dimuat.");}finally{if(alive.current&&!silent)setBusy(false);}}
 useEffect(()=>{alive.current=true;if(lookup){const fragment=window.location.hash.slice(1);if(/^[a-f0-9]{64}$/.test(fragment))token.current=fragment;}void load();const timer=setInterval(()=>{if(document.visibilityState==="visible"&&current.current&&!["delivered","returned","cancelled"].includes(current.current.stage))void load(true);},60000);return()=>{alive.current=false;clearInterval(timer);};},[lookup]);
 async function find(e:FormEvent){e.preventDefault();setBusy(true);setError("");setInfo("");try{const r=await fetch("/api/order/tracking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoice,phone}),signal:AbortSignal.timeout(45000)}),v=await r.json() as CustomerTracking&{error?:string};if(!r.ok||v.error)throw new Error(v.error||"Pesanan belum ditemukan.");const t=v.accessUrl?.split("#")[1];if(t&&/^[a-f0-9]{64}$/.test(t)){token.current=t;window.history.replaceState(null,"",window.location.pathname+"#"+t);}setData(v);setPhone("");}catch(e){setError(e instanceof Error?e.message:"Pesanan belum ditemukan.");}finally{setBusy(false);}}
 async function copy(){if(!data?.accessUrl)return;setInfo("");try{await navigator.clipboard.writeText(data.accessUrl);setInfo("Tautan pelacakan berhasil disalin. Simpan untuk membuka pesanan di perangkat lain.");}catch{setInfo("Tautan belum dapat disalin. Buka halaman pelacakan dan simpan alamatnya.");}}
 return <section className="customer-tracking" aria-label="Pelacakan pesanan"><div className="tracking-heading"><Package size={22}/><h2>Perjalanan pesanan</h2>{data&&<Button className="secondary" disabled={busy} onClick={()=>void load()} aria-label="Perbarui status pesanan"><RefreshCw size={16}/>Perbarui</Button>}</div>
 {busy&&!data&&<p role="status">Memuat status pesanan…</p>}{error&&<p className="notice error" role="alert">{error}</p>}{info&&<p className="notice success" role="status">{info}</p>}
 {data?<><p className="tracking-invoice">{data.invoice}{data.simulation?" · SIMULASI SANDBOX":""}</p><p className="tracking-state"><b>{trackingStageLabels[data.stage]}</b></p><p className="tracking-message">{data.message}</p>{data.awb&&<dl className="tracking-resi"><dt>Nomor resi</dt><dd>{data.awb}</dd><dt>Kurir</dt><dd>{data.courier}</dd></dl>}{data.lastStatus&&<p className="tracking-carrier-status">Status kurir: {data.lastStatus}</p>}{data.checkedAt&&<p className="field-help">Diperiksa {dateLabel(data.checkedAt)}</p>}
 {data.events.length>0&&<ol className="tracking-timeline">{data.events.map((event,i)=><li key={i}><time>{event.date.replace("T"," ")||"Waktu belum tersedia"}</time><b>{event.status||event.code||"Pembaruan kurir"}</b><p>{event.description}</p></li>)}</ol>}
 {data.accessUrl&&<div className="action-row tracking-actions"><Link href={data.accessUrl} className="secondary link-button">Buka halaman pelacakan</Link><Button className="secondary" onClick={()=>void copy()}><Copy size={16}/>Salin tautan</Button></div>}</>:!busy&&lookup?<form onSubmit={find}><p>Masukkan invoice dan nomor HP penerima yang digunakan saat membeli.</p><label htmlFor="tracking-invoice">Nomor invoice<input id="tracking-invoice" required value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="EV-261006-XXXXXXXX" maxLength={30} autoComplete="off"/></label><label htmlFor="tracking-phone">Nomor HP penerima<input id="tracking-phone" type="tel" required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="08xxxxxxxxxx" maxLength={20} autoComplete="tel"/></label><Button className="primary full" disabled={busy}>Cek perjalanan paket</Button></form>:!busy&&<p><Link href="/lacak">Buka pelacakan dengan invoice dan nomor HP penerima.</Link></p>}
 </section>;
}
