import {observe,proofObserved} from '@/modules/analytics/server';
import {watch} from '@/modules/analytics/errors';
import { api,json,originCheck,myOrder,publicOrder,db,bucket,image,random,notify,AppError,rate } from "@/modules/order/order-server";
import { paymentConfig,paymentAvailable } from "@/modules/order/payment-config";
import { storedPaymentMethod } from "@/modules/order/payment-types";
export const POST=(r:Request)=>watch(r,'proof_upload_error',()=>api(async()=>{originCheck(r);const o=await myOrder(r);if(o.proof_key){await observe(()=>proofObserved(o.id));return json(publicOrder(o));}await rate(r,"proof",15);const {bytes,mime,form}=await image(r);if([...form.keys()].some(k=>k!=="file"&&k!=="paymentMethod"))throw new AppError(400,"Data pembayaran tidak boleh diubah melalui unggahan bukti.");const method=storedPaymentMethod(o.payment_method);if(method==="bca_transfer"&&!form.has("paymentMethod"))throw new AppError(409,"Muat ulang halaman dan pilih metode pembayaran yang digunakan sebelum mengirim bukti.");if(form.has("paymentMethod")&&form.get("paymentMethod")!==method)throw new AppError(409,"Metode pembayaran berubah. Muat ulang sebelum mengirim bukti.");if(!paymentAvailable(await paymentConfig(),method))throw new AppError(409,"Metode pembayaran ini sedang tidak tersedia. Hubungi ELITE.VTG.");const key="proof/"+random();await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});const result=await db().prepare("UPDATE orders SET proof_key=?,proof_mime=?,status='submitted',payment_state='proof_received' WHERE id=? AND proof_key IS NULL AND status='awaiting_proof' AND payment_method=? AND total=? AND items_json IS ? AND shipping_json IS ? RETURNING id").bind(key,mime,o.id,method,o.total,o.items_json??null,o.shipping_json??null).first();if(!result){await bucket().delete(key);throw new AppError(409,"Pesanan atau metode pembayaran berubah dari tab lain. Muat ulang halaman.");}await observe(()=>proofObserved(o.id));await notify(o.id);return json(publicOrder(await myOrder(r)));}));

export const runtime="nodejs";
export const dynamic="force-dynamic";
