import { AppError,settings,db,encrypt,decrypt,text } from "@/modules/order/order-server";
import { defaultShippingConfig,type ShippingConfig,type KomshipLocation } from "@/modules/order/fulfilment-types";
import { Komship,normalize } from "@/modules/order/komship";
export function readShippingConfig(value?:string|null):ShippingConfig{if(!value)return {...defaultShippingConfig};try{return {...defaultShippingConfig,...JSON.parse(value)};}catch{return {...defaultShippingConfig,enabled:false};}}
export async function shippingSettings(){const s=await settings();return {config:readShippingConfig(s?.shipping_config),hasKey:!!s?.shipping_cipher,webhookActive:!!s?.webhook_active,telegramReady:!!(s?.bot_cipher&&s.chat_id)};}
export function validOrigin(origin:KomshipLocation|null){return !!(origin&&origin.postcode==="40375"&&normalize(origin.district)==="BALEENDAH"&&normalize(origin.city)==="BANDUNG");}
export async function shippingClient(environment?:string){const s=await settings();if(!s?.shipping_cipher)throw new AppError(409,"Masukkan API key Shipping Delivery Komship di pengaturan pemilik.");const cfg=readShippingConfig(s.shipping_config);return new Komship(await decrypt(s.shipping_cipher),environment==="sandbox"?"sandbox":environment==="production"?"production":cfg.environment);}
export async function saveShippingSettings(v:Record<string,unknown>){const prev=await settings(),old=readShippingConfig(prev?.shipping_config);const raw=v.config as Record<string,unknown>;if(!raw||typeof raw!=="object")throw new AppError(400,"Pengaturan pengiriman belum lengkap.");const c:ShippingConfig={...old,enabled:raw.enabled===true,environment:raw.environment==="sandbox"?"sandbox":"production",senderName:text(raw.senderName,"Nama pengirim",2,100),senderPhone:text(raw.senderPhone,"HP pengirim",9,20),senderAddress:text(raw.senderAddress,"Alamat pengirim",15,650),senderPostcode:"40375",senderEmail:typeof raw.senderEmail==="string"?raw.senderEmail.trim():"",origin:raw.origin as KomshipLocation|null,defaultGrams:Number(raw.defaultGrams),length:Number(raw.length),width:Number(raw.width),height:Number(raw.height),pickupTime:String(raw.pickupTime),pickupVehicle:raw.pickupVehicle==="Mobil"?"Mobil":raw.pickupVehicle==="Truk"?"Truk":"Motor",pickupDay:raw.pickupDay==="next_day"?"next_day":"same_or_next",labelPage:raw.labelPage==="page_1"?"page_1":raw.labelPage==="page_5"?"page_5":"page_6"};
 if(!/^(?:62|0)\d{8,13}$/.test(c.senderPhone)||!Number.isSafeInteger(c.defaultGrams)||c.defaultGrams<100||c.defaultGrams>30000||![c.length,c.width,c.height].every(n=>Number.isFinite(n)&&n>=0&&n<=150)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(c.pickupTime))throw new AppError(400,"Nomor HP, berat, ukuran paket, atau jam pickup belum valid.");
 if(c.senderEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.senderEmail))throw new AppError(400,"Email pengirim belum valid.");
 const key=typeof v.key==="string"?v.key.trim():"";if(key&&(!/^[A-Za-z0-9_.:-]{10,200}$/.test(key)))throw new AppError(400,"Format API key Shipping Delivery belum valid.");
 if(c.environment!==old.environment&&!key&&prev?.shipping_cipher)throw new AppError(409,"Masukkan key yang sesuai ketika mengganti lingkungan sandbox/produksi.");
 const provider=key?new Komship(key,c.environment):prev?.shipping_cipher?await shippingClient():null;
 if(c.origin){if(!provider||!validOrigin(c.origin))throw new AppError(400,"Pilih wilayah asal Komship yang sesuai Baleendah 40375.");const rows=await provider.search("40375"),match=rows.find(r=>r.id===Number(c.origin!.id));if(!match||!validOrigin(match))throw new AppError(409,"Kode wilayah asal belum terverifikasi Komship.");c.origin=match;}
 if(c.enabled&&(!provider||!c.origin||!c.senderEmail||!c.length||!c.width||!c.height))throw new AppError(409,"Lengkapi key, wilayah asal, email, dan ukuran paket sebelum mengaktifkan booking.");
 await db().prepare("UPDATE settings SET shipping_config=?,shipping_cipher=COALESCE(?,shipping_cipher) WHERE id=1").bind(JSON.stringify(c),key?await encrypt(key):null).run();return c;
}
