import { AppError,settings,db,encrypt,decrypt,text } from "@/modules/order/order-server";
import { defaultShippingConfig,type ShippingConfig } from "@/modules/order/fulfilment-types";
import { KiriminAja,validKiriminOrigin } from "@/modules/order/kiriminaja";
export { readShippingConfig,validOrigin,shippingClient } from "@/modules/order/legacy-shipping-settings";
import { readShippingConfig } from "@/modules/order/legacy-shipping-settings";

export async function kiriminSettings(){const s=await settings();const old=readShippingConfig(s?.shipping_config);return {settings:s,config:s?.kirimin_config?readShippingConfig(s.kirimin_config):{...defaultShippingConfig,senderName:old.senderName,senderPhone:old.senderPhone,senderAddress:old.senderAddress,senderEmail:old.senderEmail,defaultGrams:old.defaultGrams,length:old.length,width:old.width,height:old.height,pickupTime:old.pickupTime,pickupDay:old.pickupDay,labelPage:old.labelPage}};}
export async function shippingSettings(){const {settings:s,config}=await kiriminSettings();return {config,provider:"kiriminaja",hasKey:!!s?.kirimin_cipher,hasPin:!!s?.kirimin_pin_cipher,webhookActive:!!s?.webhook_active,telegramReady:!!(s?.bot_cipher&&s.chat_id),kiriminWebhookActive:!!s?.kirimin_webhook_active,ratesReady:!!(s?.kirimin_cipher&&config.environment==="production"&&validKiriminOrigin(config.origin)),bookingReady:!!(config.enabled&&s?.kirimin_cipher&&s?.kirimin_pin_cipher&&validKiriminOrigin(config.origin))};}
export async function kiriminClient(environment?:string){const {settings:s,config}=await kiriminSettings();if(!s?.kirimin_cipher)throw new AppError(409,"Masukkan API key KiriminAja pada pengaturan pemilik.");if(environment&&environment!==config.environment)throw new AppError(409,"Kembalikan lingkungan dan API key KiriminAja sesuai booking yang sudah dibuat.");return new KiriminAja(await decrypt(s.kirimin_cipher),config.environment);}
export async function kiriminPin(){const s=await settings();if(!s?.kirimin_pin_cipher)throw new AppError(409,"Masukkan PIN KA Credit pada pengaturan pemilik.");return decrypt(s.kirimin_pin_cipher);}
export async function kiriminRatesReady(){const {settings:s,config}=await kiriminSettings();return !!(s?.kirimin_cipher&&config.environment==="production"&&validKiriminOrigin(config.origin));}
export function validCoordinatePair(latitude:unknown,longitude:unknown){return typeof latitude==="number"&&typeof longitude==="number"&&Number.isFinite(latitude)&&Number.isFinite(longitude)&&latitude>=-11&&latitude<=6&&longitude>=95&&longitude<=141;}
export async function saveShippingSettings(v:Record<string,unknown>){
 const {settings:prev,config:old}=await kiriminSettings(),raw=v.config as Record<string,unknown>;if(!raw||typeof raw!=="object")throw new AppError(400,"Pengaturan pengiriman belum lengkap.");
 const c:ShippingConfig={...old,enabled:raw.enabled===true,environment:raw.environment==="sandbox"?"sandbox":"production",senderName:text(raw.senderName,"Nama pengirim",2,100),senderPhone:text(raw.senderPhone,"HP pengirim",9,20),senderAddress:text(raw.senderAddress,"Alamat pengirim",15,230),senderPostcode:"40375",senderEmail:typeof raw.senderEmail==="string"?raw.senderEmail.trim():"",origin:raw.origin as ShippingConfig["origin"],defaultGrams:Number(raw.defaultGrams),length:Number(raw.length),width:Number(raw.width),height:Number(raw.height),pickupTime:String(raw.pickupTime),pickupVehicle:"Motor",pickupDay:raw.pickupDay==="next_day"?"next_day":"same_or_next",labelPage:raw.labelPage==="page_1"?"page_1":raw.labelPage==="page_5"?"page_5":"page_6",senderLatitude:raw.senderLatitude==null||raw.senderLatitude===""?null:Number(raw.senderLatitude),senderLongitude:raw.senderLongitude==null||raw.senderLongitude===""?null:Number(raw.senderLongitude)};
 if(!/^(?:62|0)\d{8,13}$/.test(c.senderPhone)||!Number.isSafeInteger(c.defaultGrams)||c.defaultGrams<100||c.defaultGrams>30000||![c.length,c.width,c.height].every(n=>Number.isFinite(n)&&n>=0&&n<=150)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(c.pickupTime)||c.pickupTime>="16:00")throw new AppError(400,"Nomor HP, berat, ukuran, atau jadwal pickup belum valid. Pilih pickup sebelum 16.00 WIB.");
 if((c.senderLatitude!=null||c.senderLongitude!=null)&&!validCoordinatePair(c.senderLatitude,c.senderLongitude))throw new AppError(400,"Koordinat pengirim harus berada di Indonesia dan diisi berpasangan.");
 const key=typeof v.key==="string"?v.key.trim():"",pin=typeof v.pin==="string"?v.pin.trim():"";
 if(key&&(key.length<10||key.length>512||/\s/.test(key)))throw new AppError(400,"API key KiriminAja belum valid.");if(pin&&!/^\d{6}$/.test(pin))throw new AppError(400,"PIN KA Credit harus 6 digit.");
 const changing=c.environment!==old.environment;if(changing&&!key&&prev?.kirimin_cipher)throw new AppError(409,"Masukkan API key yang sesuai saat mengganti lingkungan API.");
 const provider=key?new KiriminAja(key,c.environment):prev?.kirimin_cipher?await kiriminClient():null;
 if(c.origin){if(!provider||!validKiriminOrigin(c.origin))throw new AppError(400,"Pilih wilayah KiriminAja di Baleendah, Kabupaten Bandung, 40375.");const match=(await provider.search("40375",true)).find(r=>r.id===c.origin!.id&&r.districtId===c.origin!.districtId);if(!match||!validKiriminOrigin(match))throw new AppError(409,"Wilayah asal belum terverifikasi KiriminAja.");c.origin=match;}
 const retainedPin=!changing&&!key?prev?.kirimin_pin_cipher:null;
 if(c.enabled&&(!provider||!c.origin||(!pin&&!retainedPin)||![c.length,c.width,c.height].every(n=>n>=1)))throw new AppError(409,"Lengkapi API key, PIN KA Credit, wilayah asal, dan ukuran paket sebelum mengaktifkan booking.");
 await db().prepare("UPDATE settings SET kirimin_config=?,kirimin_cipher=COALESCE(?,kirimin_cipher),kirimin_pin_cipher=?,kirimin_webhook_active=? WHERE id=1").bind(JSON.stringify(c),key?await encrypt(key):null,pin?await encrypt(pin):retainedPin,key||changing?0:prev?.kirimin_webhook_active||0).run();return c;
}
