import { env } from '@/lib/env';
import { AppError,db,settings,decrypt,encrypt,random,telegram,hash,type Settings } from "@/modules/order/order-server";
export async function ensureTelegramWebhook(supplied?:Settings|null){const s=supplied||await settings();if(!s?.bot_cipher||!s.chat_id)throw new AppError(409,"Hubungkan bot dan akun Telegram pemilik dahulu.");if(s.webhook_active&&s.webhook_cipher)return;
 const origin=env.SITE_ORIGIN;if(!origin?.startsWith("https://"))throw new AppError(503,"Alamat webhook Telegram belum tersedia.");const token=await decrypt(s.bot_cipher),url=origin+"/api/telegram/webhook",hook=await telegram<{url:string}>(token,"getWebhookInfo",{});if(hook.url&&hook.url!==url)throw new AppError(409,"Webhook bot terhubung ke aplikasi lain. Periksa koneksi sebelum mengaktifkan konfirmasi.");
 const secret=s.webhook_cipher?await decrypt(s.webhook_cipher):random();await db().prepare("UPDATE settings SET webhook_cipher=? WHERE id=1").bind(await encrypt(secret)).run();await telegram(token,"setWebhook",{url,secret_token:secret,allowed_updates:["message","callback_query"],max_connections:4,drop_pending_updates:false});await db().prepare("UPDATE settings SET webhook_active=1 WHERE id=1").run();
}
export async function verifyTelegramRequest(req:Request,s:Settings|null){if(!s?.webhook_cipher||!s.bot_cipher||!s.webhook_active)throw new AppError(403,"Webhook belum aktif.");const header=req.headers.get("x-telegram-bot-api-secret-token")||"";const expected=await decrypt(s.webhook_cipher);if(await hash(header)!==await hash(expected))throw new AppError(403,"Permintaan Telegram tidak sah.");}
export type Callback={id:string;from:{id:number;is_bot?:boolean};data?:string;message?:{message_id:number;chat:{id:number;type:string}}};
export function verifyCallback(c:Callback,s:Settings){if(c.from?.is_bot||String(c.from?.id)!==s.chat_id||c.message?.chat.type!=="private"||String(c.message.chat.id)!==s.chat_id)throw new AppError(403,"Hanya akun Telegram pemilik yang boleh mengonfirmasi.");}
