import { env } from '@/lib/env';
import { AppError, db } from '@/modules/catalog/server';
import { normalizeInstagramUrl } from '@/modules/catalog/caption-parser';
export function instagramConfig(){return {token:!!env.INSTAGRAM_ACCESS_TOKEN,userId:!!env.INSTAGRAM_USER_ID,version:!!env.INSTAGRAM_API_VERSION,configured:!!(env.INSTAGRAM_ACCESS_TOKEN&&env.INSTAGRAM_USER_ID&&env.INSTAGRAM_API_VERSION)}}
function config(){if(!instagramConfig().configured)throw new AppError(503,'Instagram belum terhubung. Tempel caption dan unggah foto untuk membuat draf.',{captionStatus:'not_attempted',photoStatus:'not_attempted',parseStatus:'not_attempted'});if(!/^v\d{2}\.\d$/.test(env.INSTAGRAM_API_VERSION!)||!/^\d+$/.test(env.INSTAGRAM_USER_ID!))throw new AppError(503,'Konfigurasi ID akun atau versi API Instagram tidak valid.');return {token:env.INSTAGRAM_ACCESS_TOKEN!,id:env.INSTAGRAM_USER_ID!,version:env.INSTAGRAM_API_VERSION!}}
async function graph(path:string,fields:string,after?:string){const c=config();const url=new URL(`https://graph.instagram.com/${c.version}/${path}`);url.searchParams.set('fields',fields);url.searchParams.set('access_token',c.token);if(path.endsWith('/media'))url.searchParams.set('limit','100');if(after)url.searchParams.set('after',after);let res:Response;try{res=await fetch(url,{signal:AbortSignal.timeout(12000),redirect:'error'})}catch{throw new AppError(502,'Meta belum dapat dihubungi. Input Anda tetap tersimpan di formulir.')}let data:any;try{data=await res.json()}catch{throw new AppError(502,'Jawaban Meta tidak dapat dibaca. Gunakan input caption manual.')}if(!res.ok||data.error){const code=data.error?.code;throw new AppError(502,code===190?'Token Instagram ditolak atau kedaluwarsa. Perbarui token di server.':code===10||code===200?'Izin akun Instagram belum cukup. Periksa instagram_business_basic dan otorisasi akun ELITE.':'Permintaan Instagram gagal. Periksa akun, izin, token, dan versi API di server.')}return data}
export async function checkInstagram(){const c=config();const me=await graph(c.id,'id,username');if(String(me.id)!==c.id)throw new AppError(502,'Identitas akun dari Meta tidak cocok dengan konfigurasi.');return {state:'verified',username:me.username??null,checkedAt:new Date().toISOString()}}
export async function fetchInstagramPost(raw:string){const normalized=normalizeInstagramUrl(raw);const c=config();let after:string|undefined;for(let page=0;page<10;page++){const data=await graph(`${c.id}/media`,'id,caption,media_type,media_url,thumbnail_url,permalink,children{id,media_type,media_url,thumbnail_url}',after);const media=Array.isArray(data.data)?data.data:[];for(const item of media){try{if(normalizeInstagramUrl(item.permalink??'').shortcode!==normalized.shortcode)continue}catch{continue}const first=item.media_type==='CAROUSEL_ALBUM'?item.children?.data?.[0]:item;const photo=first?.media_type==='VIDEO'?first.thumbnail_url:first?.media_url;return {caption:typeof item.caption==='string'?item.caption:'',photoUrl:typeof photo==='string'?photo:null,mediaId:String(item.id),url:normalized.url,shortcode:normalized.shortcode}}
 if(!data.paging?.next||!data.paging?.cursors?.after)break;after=data.paging.cursors.after;
 }throw new AppError(404,'Postingan tidak ditemukan pada 1.000 media terbaru akun yang diotorisasi. Periksa akun dan link, atau gunakan caption manual.');}
export async function logImport(url:string,source:string,captionStatus:string,photoStatus:string,parseStatus:string,message:string){await db().prepare('INSERT INTO import_attempts (id,instagram_url,source,caption_status,photo_status,parse_status,message,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),url,source,captionStatus,photoStatus,parseStatus,message,new Date().toISOString()).run()}
