import {db,AppError,textValue} from '@/modules/catalog/server';
import {CATEGORIES,FEATURE_GROUPS,type Feature,type Taxonomy,termKey} from '@/modules/catalog/taxonomy';
export async function readTaxonomy():Promise<Taxonomy>{const d=db();const [terms,aliases]=await Promise.all([d.prepare('SELECT * FROM catalog_features ORDER BY sort_order,label,id').all(),d.prepare('SELECT * FROM feature_aliases ORDER BY alias_key').all()]);return {categories:CATEGORIES,groups:FEATURE_GROUPS,features:terms.results.map((r:any)=>({id:r.id,label:r.label,groupId:r.group_id,aliases:aliases.results.filter((a:any)=>a.feature_id===r.id).map((a:any)=>a.value)}))}}
export async function validateFeatures(input:unknown){if(!Array.isArray(input)||input.length>100||input.some(id=>typeof id!=='string'||id.length>80))throw new AppError(400,'Pilih ciri tambahan dari daftar bersama.');const {features}=await readTaxonomy();const ids=[...new Set(input)] as string[];if(ids.some(id=>!features.some(f=>f.id===id)))throw new AppError(400,'Ciri tidak dikenal. Muat daftar terbaru sebelum menyimpan.');return ids}
function aliasValues(label:string,input:unknown){if(!Array.isArray(input)||input.length>20||input.some(a=>typeof a!=='string'||a.length>80))throw new AppError(400,'Maksimal 20 variasi ejaan, masing-masing 80 karakter.');const values=[label,...input as string[]].map(a=>a.trim()).filter(Boolean);if(values.some(a=>!termKey(a)||termKey(a).length<2))throw new AppError(400,'Nama ciri atau variasi ejaan tidak valid.');return [...new Map(values.map(value=>[termKey(value),{key:termKey(value),value}])).values()]}
export async function addFeature(input:any){
 const label=textValue(input.label,60),groupId=textValue(input.groupId,40);if(!label||label.length<2||!FEATURE_GROUPS.some(g=>g.id===groupId))throw new AppError(400,'Isi nama ciri dan pilih kelompoknya.');const values=aliasValues(label,input.aliases??[]),d=db();
 const canonical=await d.prepare('SELECT f.* FROM catalog_features f JOIN feature_aliases a ON a.feature_id=f.id WHERE a.alias_key=?').bind(termKey(label)).first<any>();
 if(canonical)throw new AppError(409,`Istilah ini sudah tersedia sebagai “${canonical.label}”. Pilih dari daftar yang ada.`,{existingId:canonical.id});
 for(const a of values){const exists=await d.prepare('SELECT f.label FROM feature_aliases a JOIN catalog_features f ON f.id=a.feature_id WHERE a.alias_key=?').bind(a.key).first<any>();if(exists)throw new AppError(409,`Variasi “${a.value}” sudah dipakai oleh ${exists.label}.`)}
 const id=crypto.randomUUID();try{await d.batch([d.prepare('INSERT INTO catalog_features(id,label,group_id,sort_order) VALUES(?,?,?,(SELECT COALESCE(MAX(sort_order),0)+1 FROM catalog_features))').bind(id,label,groupId),...values.map(a=>d.prepare('INSERT INTO feature_aliases(alias_key,feature_id,value) VALUES(?,?,?)').bind(a.key,id,a.value))])}catch{throw new AppError(409,'Istilah sudah ditambahkan admin lain. Muat ulang daftar ciri.')}
 return readTaxonomy();
}
export async function addAliases(input:any){const id=textValue(input.id,80),d=db();const feature=await d.prepare('SELECT * FROM catalog_features WHERE id=?').bind(id).first<any>();if(!feature)throw new AppError(404,'Ciri tidak ditemukan.');const values=aliasValues(feature.label,input.aliases??[]),statements=[];for(const a of values){const found=await d.prepare('SELECT feature_id FROM feature_aliases WHERE alias_key=?').bind(a.key).first<any>();if(found&&found.feature_id!==id)throw new AppError(409,`Variasi “${a.value}” sudah dipakai ciri lain.`);if(!found)statements.push(d.prepare('INSERT INTO feature_aliases(alias_key,feature_id,value) VALUES(?,?,?)').bind(a.key,id,a.value))}if(statements.length)try{await d.batch(statements)}catch{throw new AppError(409,'Variasi ejaan berubah dari admin lain. Muat ulang daftar.')};return readTaxonomy()}
